const fs = require('fs');

let fileContent = fs.readFileSync('questions.js', 'utf8');
const match = fileContent.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
if (!match) {
  console.log("Could not find QUESTIONS");
  process.exit(1);
}
const questionsObj = JSON.parse(match[1]);

function rotateAnswers(questions, startIdx) {
  let count = startIdx;
  const labels = ["A", "B", "C", "D"];
  return questions.map(q => {
    let correctIdx = count % 4;
    count++;
    let originalCorrectText = q.options.find(o => o.is_correct).text;
    let incorrectTexts = q.options.filter(o => !o.is_correct).map(o => o.text);
    
    let newOpts = [];
    let incCount = 0;
    for (let i = 0; i < 4; i++) {
      if (i === correctIdx) {
        newOpts.push({ label: labels[i], text: originalCorrectText, is_correct: true });
      } else {
        newOpts.push({ label: labels[i], text: incorrectTexts[incCount++], is_correct: false });
      }
    }
    q.options = newOpts;
    q.solution.final_answer = labels[correctIdx];
    return q;
  });
}

const modelingNew = [
  // Decision Analysis (8)
  { topic: "Decision Analysis", title: "Expected Monetary Value", question: "A project has a 40% chance of a $100,000 profit and a 60% chance of a $20,000 loss. What is the Expected Monetary Value (EMV)?", options: [ { text: "$28,000", is_correct: true }, { text: "$40,000", is_correct: false }, { text: "$12,000", is_correct: false }, { text: "$80,000", is_correct: false } ], solution: { steps: [ { title: "Calculate EMV", content: "EMV = (0.40 * 100000) + (0.60 * -20000) = 40000 - 12000 = 28000." } ] } },
  { topic: "Decision Analysis", title: "Maximin Criterion", question: "A pessimistic decision maker using the Maximin criterion will choose the alternative that maximizes the:", options: [ { text: "Minimum possible payoff", is_correct: true }, { text: "Maximum possible payoff", is_correct: false }, { text: "Expected value", is_correct: false }, { text: "Maximum regret", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Maximin is 'maximize the minimum', suitable for risk-averse individuals." } ] } },
  { topic: "Decision Analysis", title: "Maximax Criterion", question: "An optimistic decision maker using the Maximax criterion will choose the alternative that maximizes the:", options: [ { text: "Maximum possible payoff", is_correct: true }, { text: "Minimum possible payoff", is_correct: false }, { text: "Expected value", is_correct: false }, { text: "Expected regret", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Maximax is 'maximize the maximum', suitable for risk-seeking individuals." } ] } },
  { topic: "Decision Analysis", title: "Minimax Regret", question: "The Minimax Regret criterion seeks to minimize the maximum:", options: [ { text: "Opportunity loss", is_correct: true }, { text: "Monetary loss", is_correct: false }, { text: "Initial investment", is_correct: false }, { text: "Variance of returns", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Regret is defined as opportunity loss (best possible payoff - actual payoff)." } ] } },
  { topic: "Decision Analysis", title: "Decision Trees", question: "In a decision tree, what does a square node represent?", options: [ { text: "A decision point where the decision maker chooses an alternative", is_correct: true }, { text: "A chance event with probabilities", is_correct: false }, { text: "A final outcome or payoff", is_correct: false }, { text: "A calculation step", is_correct: false } ], solution: { steps: [ { title: "Notation", content: "Squares = Decisions. Circles = Chance events. Triangles = Endpoints." } ] } },
  { topic: "Decision Analysis", title: "Expected Value of Perfect Information", question: "The Expected Value of Perfect Information (EVPI) is defined as:", options: [ { text: "Expected payoff under certainty minus the maximum EMV", is_correct: true }, { text: "Maximum EMV minus minimum EMV", is_correct: false }, { text: "The cost of hiring a consultant", is_correct: false }, { text: "The variance of the best alternative", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "EVPI = Expected Payoff with Perfect Information (EPPI) - Max EMV." } ] } },
  { topic: "Decision Analysis", title: "Utility Theory", question: "A utility function that is concave downward (e.g., $U(x) = \\sqrt{x}$) represents a decision maker who is:", options: [ { text: "Risk averse", is_correct: true }, { text: "Risk neutral", is_correct: false }, { text: "Risk seeking", is_correct: false }, { text: "Irrational", is_correct: false } ], solution: { steps: [ { title: "Risk Profile", content: "Diminishing marginal utility corresponds to risk aversion." } ] } },
  { topic: "Decision Analysis", title: "Certainty Equivalent", question: "The certainty equivalent of a lottery is the guaranteed amount that yields the same _____ as the expected _____ of the lottery.", options: [ { text: "Utility / Utility", is_correct: true }, { text: "Payoff / Utility", is_correct: false }, { text: "Utility / Payoff", is_correct: false }, { text: "Payoff / Payoff", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "$U(CE) = E[U(Lottery)]$." } ] } },

  // Dynamic Programming (9)
  { topic: "Dynamic Programming", title: "Bellman's Principle", question: "Bellman's Principle of Optimality states that an optimal policy has the property that:", options: [ { text: "Whatever the initial state and decisions, the remaining decisions must constitute an optimal policy", is_correct: true }, { text: "The local optimum is always the global optimum", is_correct: false }, { text: "Dynamic programming only works for linear models", is_correct: false }, { text: "The future is independent of the past", is_correct: false } ], solution: { steps: [ { title: "Principle", content: "This is the fundamental justification for breaking down DP problems into stages." } ] } },
  { topic: "Dynamic Programming", title: "DP Stages", question: "In a dynamic programming problem, the problem is divided into subproblems called:", options: [ { text: "Stages", is_correct: true }, { text: "Nodes", is_correct: false }, { text: "Simplexes", is_correct: false }, { text: "Heuristics", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "DP problems are solved stage by stage, often moving backward in time." } ] } },
  { topic: "Dynamic Programming", title: "State Variables", question: "In DP, the information that summarizes the current status of the system is called the:", options: [ { text: "State", is_correct: true }, { text: "Decision variable", is_correct: false }, { text: "Return function", is_correct: false }, { text: "Transition function", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "State variables contain all necessary information to make future decisions." } ] } },
  { topic: "Dynamic Programming", title: "Backward Induction", question: "Most dynamic programming problems are solved using:", options: [ { text: "Backward induction", is_correct: true }, { text: "Forward propagation", is_correct: false }, { text: "Simplex method", is_correct: false }, { text: "Branch and bound", is_correct: false } ], solution: { steps: [ { title: "Methodology", content: "Solving from the last stage back to the first is the standard approach." } ] } },
  { topic: "Dynamic Programming", title: "Knapsack Problem", question: "The 0/1 Knapsack problem can be solved optimally using DP. In its DP formulation, what typically serves as the state variable?", options: [ { text: "The remaining capacity of the knapsack", is_correct: true }, { text: "The value of the current item", is_correct: false }, { text: "The total weight of all available items", is_correct: false }, { text: "The number of items left to consider", is_correct: false } ], solution: { steps: [ { title: "Formulation", content: "State = (item index $i$, remaining capacity $w$)." } ] } },
  { topic: "Dynamic Programming", title: "Shortest Path DP", question: "When finding the shortest path through a layered network using DP, the recursive equation calculates:", options: [ { text: "The minimum cost from the current node to the destination", is_correct: true }, { text: "The minimum cost from the origin to the current node", is_correct: false }, { text: "The longest path to the destination", is_correct: false }, { text: "The average cost of all paths", is_correct: false } ], solution: { steps: [ { title: "Formulation", content: "$f_n(s) = \\min_x \\{ c_{sx} + f_{n+1}(x) \\}$." } ] } },
  { topic: "Dynamic Programming", title: "Curse of Dimensionality", question: "A major computational challenge in dynamic programming when the state space grows exponentially is known as:", options: [ { text: "The curse of dimensionality", is_correct: true }, { text: "The combinatorial explosion", is_correct: false }, { text: "The traveling salesman problem", is_correct: false }, { text: "Degeneracy", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Coined by Richard Bellman to describe the rapid increase in volume associated with adding extra dimensions." } ] } },
  { topic: "Dynamic Programming", title: "Markov Decision Process", question: "An extension of dynamic programming where transitions between states are stochastic is called a:", options: [ { text: "Markov Decision Process (MDP)", is_correct: true }, { text: "Linear Program", is_correct: false }, { text: "Simulation", is_correct: false }, { text: "Decision Tree", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "MDPs involve states, actions, transition probabilities, and rewards." } ] } },
  { topic: "Dynamic Programming", title: "Deterministic vs Stochastic", question: "In a deterministic dynamic programming model, the state at the next stage is completely determined by:", options: [ { text: "The current state and current decision", is_correct: true }, { text: "A probability distribution", is_correct: false }, { text: "The initial state only", is_correct: false }, { text: "The final desired state", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "There is no uncertainty in state transitions in deterministic DP." } ] } },

  // Linear Programming (7)
  { topic: "Linear Programming", title: "Feasible Region", question: "In a linear programming problem, the set of all points that satisfy all constraints is called the:", options: [ { text: "Feasible region", is_correct: true }, { text: "Optimal region", is_correct: false }, { text: "Objective region", is_correct: false }, { text: "Simplex space", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "The feasible region represents all valid solutions." } ] } },
  { topic: "Linear Programming", title: "Simplex Method", question: "The Simplex Method solves LP problems by moving along the edges of the feasible region to adjacent:", options: [ { text: "Corner points (extreme points)", is_correct: true }, { text: "Interior points", is_correct: false }, { text: "Centroids", is_correct: false }, { text: "Origins", is_correct: false } ], solution: { steps: [ { title: "Mechanism", content: "The optimal solution to an LP always lies at a corner point (or edge)." } ] } },
  { topic: "Linear Programming", title: "Shadow Price", question: "The shadow price (dual price) of a constraint in LP represents:", options: [ { text: "The change in the optimal objective value for a one-unit increase in the RHS of the constraint", is_correct: true }, { text: "The cost of the raw material", is_correct: false }, { text: "The penalty for violating the constraint", is_correct: false }, { text: "The profit per unit of product", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "It is the marginal value of the resource." } ] } },
  { topic: "Linear Programming", title: "Unbounded Solution", question: "An LP problem is unbounded if:", options: [ { text: "The objective function can be increased (or decreased) indefinitely without violating any constraints", is_correct: true }, { text: "There is no feasible region", is_correct: false }, { text: "There are multiple optimal solutions", is_correct: false }, { text: "The constraints are linearly dependent", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Unbounded means the optimal value is infinity." } ] } },
  { topic: "Linear Programming", title: "Infeasible Problem", question: "If the constraints in an LP problem contradict each other such that no point satisfies all of them simultaneously, the problem is:", options: [ { text: "Infeasible", is_correct: true }, { text: "Unbounded", is_correct: false }, { text: "Degenerate", is_correct: false }, { text: "Sub-optimal", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "An empty feasible region means no solution exists." } ] } },
  { topic: "Linear Programming", title: "Slack Variables", question: "To convert a 'less than or equal to' ($\\le$) inequality constraint into an equality for the Simplex method, one must add a:", options: [ { text: "Slack variable", is_correct: true }, { text: "Surplus variable", is_correct: false }, { text: "Artificial variable", is_correct: false }, { text: "Decision variable", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Slack variables represent unused resources." } ] } },
  { topic: "Linear Programming", title: "Duality Theorem", question: "The Strong Duality Theorem states that if the primal LP has an optimal solution, then:", options: [ { text: "The dual LP also has an optimal solution and their objective values are equal", is_correct: true }, { text: "The dual LP is unbounded", is_correct: false }, { text: "The dual LP is infeasible", is_correct: false }, { text: "The dual optimal value is zero", is_correct: false } ], solution: { steps: [ { title: "Theorem", content: "$Z_{primal} = W_{dual}$ at optimality." } ] } },

  // Modeling (6)
  { topic: "Modeling", title: "Deterministic vs Stochastic Models", question: "A quantitative model that incorporates uncertainty and probability distributions is classified as:", options: [ { text: "Stochastic", is_correct: true }, { text: "Deterministic", is_correct: false }, { text: "Continuous", is_correct: false }, { text: "Static", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Stochastic means random or probabilistic." } ] } },
  { topic: "Modeling", title: "Heuristic Methods", question: "A heuristic algorithm is designed to find:", options: [ { text: "A good, feasible solution quickly, though not necessarily the optimal one", is_correct: true }, { text: "The absolute global optimum at any cost", is_correct: false }, { text: "An exact mathematical proof", is_correct: false }, { text: "A solution to a continuous differential equation", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Heuristics are rules of thumb for complex problems (like TSP)." } ] } },
  { topic: "Modeling", title: "Validation vs Verification", question: "In modeling and simulation, 'validation' refers to:", options: [ { text: "Ensuring the model accurately represents the real-world system", is_correct: true }, { text: "Ensuring the computer code is bug-free (building the model right)", is_correct: false }, { text: "Gathering input data", is_correct: false }, { text: "Running the model multiple times", is_correct: false } ], solution: { steps: [ { title: "Distinction", content: "Validation = 'building the right model'. Verification = 'building the model right'." } ] } },
  { topic: "Modeling", title: "Objective Function", question: "In mathematical modeling, the equation that represents the goal of the system (e.g., maximize profit, minimize cost) is the:", options: [ { text: "Objective function", is_correct: true }, { text: "Constraint function", is_correct: false }, { text: "State transition function", is_correct: false }, { text: "Decision variable", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "The objective function is what is being optimized." } ] } },
  { topic: "Modeling", title: "Sensitivity Analysis", question: "Analyzing how changes in model inputs or parameters affect the optimal solution is called:", options: [ { text: "Sensitivity analysis", is_correct: true }, { text: "Regression analysis", is_correct: false }, { text: "Time series analysis", is_correct: false }, { text: "Factor analysis", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Also known as 'what-if' analysis." } ] } },
  { topic: "Modeling", title: "Constraints", question: "Mathematical inequalities or equations that restrict the values of decision variables represent:", options: [ { text: "Constraints", is_correct: true }, { text: "Objectives", is_correct: false }, { text: "Parameters", is_correct: false }, { text: "Heuristics", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Constraints represent physical, financial, or policy limits." } ] } },

  // Optimization (4)
  { topic: "Optimization", title: "Integer Programming", question: "An optimization problem where some or all of the decision variables are restricted to take only integer values is called:", options: [ { text: "Integer Programming", is_correct: true }, { text: "Linear Programming", is_correct: false }, { text: "Nonlinear Programming", is_correct: false }, { text: "Dynamic Programming", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "IP is used when fractional answers (e.g., 2.5 machines) don't make sense." } ] } },
  { topic: "Optimization", title: "Branch and Bound", question: "Which algorithm is the most common exact method used to solve Mixed Integer Programming (MIP) problems?", options: [ { text: "Branch and Bound", is_correct: true }, { text: "Simplex Method", is_correct: false }, { text: "Gradient Descent", is_correct: false }, { text: "Monte Carlo Simulation", is_correct: false } ], solution: { steps: [ { title: "Algorithm", content: "Branch and Bound systematically enumerates candidate solutions using tree search." } ] } },
  { topic: "Optimization", title: "Nonlinear Programming", question: "If the objective function or any of the constraints in an optimization problem contain terms like $x^2$ or $\\sin(x)$, the problem is classified as:", options: [ { text: "Nonlinear Programming", is_correct: true }, { text: "Linear Programming", is_correct: false }, { text: "Integer Programming", is_correct: false }, { text: "Goal Programming", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "NLP handles non-linear relationships." } ] } },
  { topic: "Optimization", title: "Global vs Local Optimum", question: "A major difficulty in solving non-convex nonlinear programming problems is that an algorithm might get trapped in a:", options: [ { text: "Local optimum", is_correct: true }, { text: "Global optimum", is_correct: false }, { text: "Degenerate point", is_correct: false }, { text: "Feasible region", is_correct: false } ], solution: { steps: [ { title: "Challenge", content: "Algorithms like gradient descent only find local minima." } ] } },

  // Queueing Theory (8)
  { topic: "Queueing Theory", title: "Kendall Notation", question: "In Kendall's notation (A/B/C) for queueing models, what does 'A' represent?", options: [ { text: "Arrival process (interarrival time distribution)", is_correct: true }, { text: "Service time distribution", is_correct: false }, { text: "Number of servers", is_correct: false }, { text: "System capacity", is_correct: false } ], solution: { steps: [ { title: "Notation", content: "A = Arrival, B = Service, C = Number of parallel servers." } ] } },
  { topic: "Queueing Theory", title: "M/M/1 Queue", question: "An M/M/1 queue indicates that both interarrival and service times follow which probability distribution?", options: [ { text: "Exponential (Markovian)", is_correct: true }, { text: "Normal", is_correct: false }, { text: "Uniform", is_correct: false }, { text: "Deterministic", is_correct: false } ], solution: { steps: [ { title: "Notation", content: "'M' stands for Markovian or Memoryless, corresponding to the exponential distribution." } ] } },
  { topic: "Queueing Theory", title: "Little's Law", question: "Little's Law relates the average number of customers in the system ($L$), the arrival rate ($\\lambda$), and the average time spent in the system ($W$) via the equation:", options: [ { text: "$L = \\lambda W$", is_correct: true }, { text: "$W = \\lambda L$", is_correct: false }, { text: "$L = W / \\lambda$", is_correct: false }, { text: "$L = \\lambda + W$", is_correct: false } ], solution: { steps: [ { title: "Equation", content: "A fundamental theorem that applies to almost any stable queueing system." } ] } },
  { topic: "Queueing Theory", title: "Utilization Factor", question: "For a single-server queue, the utilization factor ($\\rho$) is calculated as the arrival rate ($\\lambda$) divided by the:", options: [ { text: "Service rate ($\\mu$)", is_correct: true }, { text: "Number of servers", is_correct: false }, { text: "Queue length", is_correct: false }, { text: "Wait time", is_correct: false } ], solution: { steps: [ { title: "Formula", content: "$\\rho = \\lambda / \\mu$. The system is stable only if $\\rho < 1$." } ] } },
  { topic: "Queueing Theory", title: "Queue Discipline", question: "FCFS (First-Come, First-Served) and LIFO (Last-In, First-Out) are examples of:", options: [ { text: "Queue disciplines", is_correct: true }, { text: "Arrival distributions", is_correct: false }, { text: "Service mechanisms", is_correct: false }, { text: "System capacities", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Queue discipline dictates the order in which customers are served." } ] } },
  { topic: "Queueing Theory", title: "M/M/1 Wait Time", question: "In an M/M/1 queue with $\\lambda = 4$ per hour and $\\mu = 5$ per hour, what is the expected time spent in the system ($W$)?", options: [ { text: "1 hour", is_correct: true }, { text: "0.2 hours", is_correct: false }, { text: "0.8 hours", is_correct: false }, { text: "5 hours", is_correct: false } ], solution: { steps: [ { title: "Formula", content: "$W = 1 / (\\mu - \\lambda) = 1 / (5 - 4) = 1$ hour." } ] } },
  { topic: "Queueing Theory", title: "M/M/1 Number in System", question: "In the same M/M/1 queue ($\\lambda=4$, $\\mu=5$), what is the expected number of customers in the system ($L$)?", options: [ { text: "4", is_correct: true }, { text: "5", is_correct: false }, { text: "1", is_correct: false }, { text: "0.8", is_correct: false } ], solution: { steps: [ { title: "Formula", content: "$L = \\lambda W = 4 \\times 1 = 4$ (or $L = \\rho / (1-\\rho) = (4/5)/(1/5) = 4$)." } ] } },
  { topic: "Queueing Theory", title: "Balking and Reneging", question: "A customer who arrives, sees a long line, and immediately decides to leave without joining the queue is said to be:", options: [ { text: "Balking", is_correct: true }, { text: "Reneging", is_correct: false }, { text: "Jockeying", is_correct: false }, { text: "Blocking", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Balking = not joining. Reneging = joining but leaving later. Jockeying = switching lines." } ] } },

  // Simulation (8)
  { topic: "Simulation", title: "Monte Carlo Simulation", question: "Monte Carlo simulation relies heavily on:", options: [ { text: "Repeated random sampling to obtain numerical results", is_correct: true }, { text: "Exact algebraic solutions to differential equations", is_correct: false }, { text: "Finding the absolute optimal solution to a linear program", is_correct: false }, { text: "Deterministic state transitions", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "It uses randomness to solve problems that might be deterministic in principle." } ] } },
  { topic: "Simulation", title: "Discrete-Event Simulation", question: "In Discrete-Event Simulation (DES), the system state changes only at:", options: [ { text: "Discrete points in time when events occur", is_correct: true }, { text: "Continuous intervals", is_correct: false }, { text: "The end of the day", is_correct: false }, { text: "Random spatial locations", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Time jumps from one event to the next, skipping inactive periods." } ] } },
  { topic: "Simulation", title: "Random Number Generation", question: "Most computer simulation software uses algorithms to generate 'random' numbers that are actually deterministic. These are called:", options: [ { text: "Pseudorandom numbers", is_correct: true }, { text: "True random numbers", is_correct: false }, { text: "Heuristic numbers", is_correct: false }, { text: "Stochastic numbers", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Algorithms like the Linear Congruential Generator create pseudorandom sequences." } ] } },
  { topic: "Simulation", title: "Inverse Transform Method", question: "The Inverse Transform Method is a technique used to:", options: [ { text: "Generate random variates from a specific probability distribution using Uniform(0,1) random numbers", is_correct: true }, { text: "Invert a matrix numerically", is_correct: false }, { text: "Transform deterministic models into stochastic ones", is_correct: false }, { text: "Calculate the inverse of a Laplace transform", is_correct: false } ], solution: { steps: [ { title: "Methodology", content: "It uses the inverse of the cumulative distribution function (CDF)." } ] } },
  { topic: "Simulation", title: "Warm-up Period", question: "In a steady-state simulation, data collected during the initial phase is often discarded to avoid initialization bias. This phase is called the:", options: [ { text: "Warm-up period", is_correct: true }, { text: "Cool-down period", is_correct: false }, { text: "Validation phase", is_correct: false }, { text: "Replication phase", is_correct: false } ], solution: { steps: [ { title: "Simulation Practice", content: "The system needs time to reach a representative steady state before data collection begins." } ] } },
  { topic: "Simulation", title: "Replications", question: "To estimate the variance of a simulation output and construct confidence intervals, an analyst should:", options: [ { text: "Run multiple independent replications of the simulation using different random number seeds", is_correct: true }, { text: "Run the simulation once for a very long time", is_correct: false }, { text: "Use the same random number seed repeatedly", is_correct: false }, { text: "Change the system parameters during the run", is_correct: false } ], solution: { steps: [ { title: "Statistical Validity", content: "Independent replications provide independent data points for statistical analysis." } ] } },
  { topic: "Simulation", title: "Entity and Resource", question: "In a typical discrete-event simulation of a manufacturing plant, a 'part' moving through the system is an _____, and a 'machine' processing it is a _____.", options: [ { text: "Entity / Resource", is_correct: true }, { text: "Resource / Entity", is_correct: false }, { text: "Event / State", is_correct: false }, { text: "Queue / Server", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Entities move and request resources. Resources have finite capacity." } ] } },
  { topic: "Simulation", title: "Time Advance Mechanism", question: "The mechanism in DES that maintains a list of scheduled future events and advances the simulation clock to the most imminent event is the:", options: [ { text: "Event calendar (or event list)", is_correct: true }, { text: "Random number generator", is_correct: false }, { text: "State variable", is_correct: false }, { text: "Routing logic", is_correct: false } ], solution: { steps: [ { title: "Simulation Engine", content: "The event calendar drives the entire simulation forward in time." } ] } }
];

const engMgmtNew = [
  // Engineering Management (3)
  { topic: "Engineering Management", title: "Management Functions", question: "Which of the following is NOT typically considered one of the core functions of management?", options: [ { text: "Drafting", is_correct: true }, { text: "Planning", is_correct: false }, { text: "Organizing", is_correct: false }, { text: "Controlling", is_correct: false } ], solution: { steps: [ { title: "Core Functions", content: "The classic functions are Planning, Organizing, Leading/Directing, and Controlling." } ] } },
  { topic: "Engineering Management", title: "Matrix Organization", question: "An organizational structure where employees report to both a functional manager and a project manager is called a:", options: [ { text: "Matrix organization", is_correct: true }, { text: "Functional organization", is_correct: false }, { text: "Projectized organization", is_correct: false }, { text: "Hierarchical organization", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Matrix structures balance functional expertise with project focus but violate the 'unity of command' principle." } ] } },
  { topic: "Engineering Management", title: "Span of Control", question: "In management theory, the 'span of control' refers to:", options: [ { text: "The number of subordinates directly reporting to a single manager", is_correct: true }, { text: "The geographical area a company operates in", is_correct: false }, { text: "The duration of a project", is_correct: false }, { text: "The financial budget controlled by a department", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "A narrow span creates a tall hierarchy, while a wide span creates a flat hierarchy." } ] } },
  
  // Organizational Behavior (7)
  { topic: "Organizational Behavior", title: "Maslow's Hierarchy", question: "According to Maslow's Hierarchy of Needs, the highest level of human need is:", options: [ { text: "Self-actualization", is_correct: true }, { text: "Esteem", is_correct: false }, { text: "Social / Belonging", is_correct: false }, { text: "Safety", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "The hierarchy goes: Physiological, Safety, Social, Esteem, Self-actualization." } ] } },
  { topic: "Organizational Behavior", title: "Theory X and Theory Y", question: "McGregor's Theory Y assumes that employees are inherently:", options: [ { text: "Self-motivated and seek responsibility", is_correct: true }, { text: "Lazy and avoid work", is_correct: false }, { text: "Motivated only by money", is_correct: false }, { text: "Incapable of creative problem-solving", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "Theory X assumes workers are lazy; Theory Y assumes they are intrinsically motivated." } ] } },
  { topic: "Organizational Behavior", title: "Herzberg's Two-Factor Theory", question: "In Herzberg's theory, factors like salary and working conditions that prevent dissatisfaction but do not inherently motivate are called:", options: [ { text: "Hygiene factors", is_correct: true }, { text: "Motivators", is_correct: false }, { text: "Self-actualizers", is_correct: false }, { text: "Expectancy factors", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "Hygiene factors (maintenance factors) must be met to avoid dissatisfaction." } ] } },
  { topic: "Organizational Behavior", title: "Expectancy Theory", question: "Vroom's Expectancy Theory states that motivation depends on Expectancy, Instrumentality, and:", options: [ { text: "Valence (the value placed on the reward)", is_correct: true }, { text: "Equity", is_correct: false }, { text: "Hygiene", is_correct: false }, { text: "Authority", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "Motivation = Expectancy $\\times$ Instrumentality $\\times$ Valence." } ] } },
  { topic: "Organizational Behavior", title: "Leadership Styles", question: "A leader who makes decisions independently without consulting their team is exhibiting which leadership style?", options: [ { text: "Autocratic", is_correct: true }, { text: "Democratic", is_correct: false }, { text: "Laissez-faire", is_correct: false }, { text: "Transformational", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Autocratic leaders maintain total control over decision making." } ] } },
  { topic: "Organizational Behavior", title: "Group Dynamics", question: "Tuckman's stages of group development proceed in which order?", options: [ { text: "Forming, Storming, Norming, Performing, Adjourning", is_correct: true }, { text: "Forming, Norming, Storming, Performing, Adjourning", is_correct: false }, { text: "Storming, Forming, Performing, Norming, Adjourning", is_correct: false }, { text: "Forming, Performing, Norming, Storming, Adjourning", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "This is the classic model for team development dynamics." } ] } },
  { topic: "Organizational Behavior", title: "Conflict Resolution", question: "A conflict resolution strategy where both parties give up something to reach a mutually acceptable agreement is called:", options: [ { text: "Compromising", is_correct: true }, { text: "Collaborating", is_correct: false }, { text: "Forcing", is_correct: false }, { text: "Avoiding", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Compromise yields a partial win-win, but is distinct from collaboration (where both fully win)." } ] } }
];

const allNewQuestions = {
  "modeling": rotateAnswers(modelingNew, 0),
  "eng-mgmt": rotateAnswers(engMgmtNew, 0)
};

for (const [subj, newQs] of Object.entries(allNewQuestions)) {
  if (questionsObj[subj]) {
    questionsObj[subj].push(...newQs);
  } else {
    questionsObj[subj] = newQs;
  }
}

const updatedJson = JSON.stringify(questionsObj, null, 4);
const prefixContent = fileContent.substring(0, fileContent.indexOf('const QUESTIONS ='));
fs.writeFileSync('questions.js', prefixContent + 'const QUESTIONS = ' + updatedJson + ';\n', 'utf8');
console.log(`Successfully added gaps for modeling and eng-mgmt.`);
