const fs = require('fs');

let fileContent = fs.readFileSync('questions.js', 'utf8');
const match = fileContent.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
if (!match) {
  console.log("Could not find QUESTIONS");
  process.exit(1);
}
const questionsObj = JSON.parse(match[1]);

function rotateAnswers(questions, startIdx) {
  let count = startIdx;
  const labels = ["A", "B", "C", "D"];
  return questions.map(q => {
    let correctIdx = count % 4;
    count++;
    let originalCorrectText = q.options.find(o => o.is_correct).text;
    let incorrectTexts = q.options.filter(o => !o.is_correct).map(o => o.text);
    
    let newOpts = [];
    let incCount = 0;
    for (let i = 0; i < 4; i++) {
      if (i === correctIdx) {
        newOpts.push({ label: labels[i], text: originalCorrectText, is_correct: true });
      } else {
        newOpts.push({ label: labels[i], text: incorrectTexts[incCount++], is_correct: false });
      }
    }
    q.options = newOpts;
    q.solution.final_answer = labels[correctIdx];
    return q;
  });
}

const mathNew = [
  // Differential Equations (5)
  { topic: "Differential Equations", title: "First-Order Linear ODE", question: "Find the general solution to the differential equation $dy/dx + 2y = 4$.", options: [ { text: "$y(x) = 2 + C e^{-2x}$", is_correct: true }, { text: "$y(x) = 4 + C e^{2x}$", is_correct: false }, { text: "$y(x) = C e^{-2x}$", is_correct: false }, { text: "$y(x) = 2x + C$", is_correct: false } ], solution: { steps: [ { title: "Integrating Factor", content: "The integrating factor is $\\mu(x) = e^{\\int 2 dx} = e^{2x}$. Multiplying through: $e^{2x} y' + 2e^{2x} y = 4e^{2x}$. Integrating: $e^{2x} y = 2e^{2x} + C$, so $y = 2 + C e^{-2x}$." } ] } },
  { topic: "Differential Equations", title: "Second-Order Homogeneous ODE", question: "What is the general solution of $y'' - 5y' + 6y = 0$?", options: [ { text: "$y = c_1 e^{2x} + c_2 e^{3x}$", is_correct: true }, { text: "$y = c_1 e^{-2x} + c_2 e^{-3x}$", is_correct: false }, { text: "$y = c_1 e^{x} + c_2 e^{6x}$", is_correct: false }, { text: "$y = c_1 \\cos(2x) + c_2 \\sin(3x)$", is_correct: false } ], solution: { steps: [ { title: "Characteristic Equation", content: "Characteristic eq: $r^2 - 5r + 6 = 0 \\implies (r-2)(r-3) = 0 \\implies r=2,3$. General solution is $y = c_1 e^{2x} + c_2 e^{3x}$." } ] } },
  { topic: "Differential Equations", title: "Initial Value Problem", question: "Solve $dy/dx = 3x^2 y$ with $y(0) = 5$.", options: [ { text: "$y = 5 e^{x^3}$", is_correct: true }, { text: "$y = 5 e^{3x}$", is_correct: false }, { text: "$y = e^{x^3} + 4$", is_correct: false }, { text: "$y = 15 x^3$", is_correct: false } ], solution: { steps: [ { title: "Separation of Variables", content: "$dy/y = 3x^2 dx \\implies \\ln|y| = x^3 + C \\implies y = A e^{x^3}$. Applying $y(0)=5$, $A = 5$." } ] } },
  { topic: "Differential Equations", title: "Laplace Transform of Derivative", question: "If $Y(s) = \\mathcal{L}\\{y(t)\\}$, what is the Laplace transform of $y''(t)$?", options: [ { text: "$s^2 Y(s) - s y(0) - y'(0)$", is_correct: true }, { text: "$s Y(s) - y(0)$", is_correct: false }, { text: "$s^2 Y(s)$", is_correct: false }, { text: "$s^2 Y(s) - y'(0)$", is_correct: false } ], solution: { steps: [ { title: "Laplace Property", content: "By definition, $\\mathcal{L}\\{y''(t)\\} = s^2 Y(s) - s y(0) - y'(0)$." } ] } },
  { topic: "Differential Equations", title: "Euler Method", question: "Using Euler's method with a step size of $h=0.1$ to solve $dy/dt = y$, $y(0)=1$, what is the estimated value of $y(0.1)$?", options: [ { text: "$1.1$", is_correct: true }, { text: "$1.01$", is_correct: false }, { text: "$1.21$", is_correct: false }, { text: "$1.05$", is_correct: false } ], solution: { steps: [ { title: "Euler Iteration", content: "$y(0.1) \\approx y(0) + h \\cdot f(t_0, y_0) = 1 + 0.1(1) = 1.1$." } ] } },
  
  // Linear Algebra (5)
  { topic: "Linear Algebra", title: "Matrix Determinant", question: "What is the determinant of a $2 \\times 2$ matrix $A = \\begin{pmatrix} 4 & 2 \\\\ 3 & 5 \\end{pmatrix}$?", options: [ { text: "14", is_correct: true }, { text: "26", is_correct: false }, { text: "6", is_correct: false }, { text: "20", is_correct: false } ], solution: { steps: [ { title: "Determinant Formula", content: "$\\det(A) = ad - bc = (4)(5) - (2)(3) = 20 - 6 = 14$." } ] } },
  { topic: "Linear Algebra", title: "Eigenvalues", question: "Find the eigenvalues of the matrix $B = \\begin{pmatrix} 1 & 0 \\\\ 0 & -3 \\end{pmatrix}$.", options: [ { text: "1, -3", is_correct: true }, { text: "-1, 3", is_correct: false }, { text: "0, 0", is_correct: false }, { text: "1, 3", is_correct: false } ], solution: { steps: [ { title: "Diagonal Matrix", content: "For a diagonal matrix, the eigenvalues are simply the entries on the main diagonal." } ] } },
  { topic: "Linear Algebra", title: "Matrix Inverse", question: "A square matrix $A$ is invertible if and only if:", options: [ { text: "Its determinant is non-zero", is_correct: true }, { text: "Its determinant is zero", is_correct: false }, { text: "It is a diagonal matrix", is_correct: false }, { text: "All its elements are positive", is_correct: false } ], solution: { steps: [ { title: "Invertibility Condition", content: "A matrix has an inverse exactly when $\\det(A) \\neq 0$." } ] } },
  { topic: "Linear Algebra", title: "Vector Dot Product", question: "Calculate the dot product of vectors $\\mathbf{u} = \\langle 2, -1, 3 \\rangle$ and $\\mathbf{v} = \\langle 1, 4, -2 \\rangle$.", options: [ { text: "-8", is_correct: true }, { text: "0", is_correct: false }, { text: "8", is_correct: false }, { text: "4", is_correct: false } ], solution: { steps: [ { title: "Dot Product", content: "$\\mathbf{u} \\cdot \\mathbf{v} = (2)(1) + (-1)(4) + (3)(-2) = 2 - 4 - 6 = -8$." } ] } },
  { topic: "Linear Algebra", title: "Cross Product Direction", question: "The cross product $\\mathbf{a} \\times \\mathbf{b}$ results in a vector that is:", options: [ { text: "Orthogonal to both $\\mathbf{a}$ and $\\mathbf{b}$", is_correct: true }, { text: "Parallel to $\\mathbf{a}$", is_correct: false }, { text: "In the same plane as $\\mathbf{a}$ and $\\mathbf{b}$", is_correct: false }, { text: "A scalar", is_correct: false } ], solution: { steps: [ { title: "Cross Product Property", content: "By definition, the cross product of two 3D vectors yields a vector normal to the plane containing them." } ] } },
  
  // Math (2)
  { topic: "Math", title: "Logarithm Properties", question: "Simplify the expression $\\log_2(8) + \\log_2(4)$.", options: [ { text: "5", is_correct: true }, { text: "12", is_correct: false }, { text: "32", is_correct: false }, { text: "7", is_correct: false } ], solution: { steps: [ { title: "Evaluate Logs", content: "$\\log_2(8) = 3$ and $\\log_2(4) = 2$. $3 + 2 = 5$. Alternatively, $\\log_2(8 \\times 4) = \\log_2(32) = 5$." } ] } },
  { topic: "Math", title: "Complex Numbers", question: "Evaluate the product of complex numbers $(2 + 3i)(1 - i)$.", options: [ { text: "$5 + i$", is_correct: true }, { text: "$2 - 3i$", is_correct: false }, { text: "$-1 + 5i$", is_correct: false }, { text: "$5 - i$", is_correct: false } ], solution: { steps: [ { title: "Foil Method", content: "$(2)(1) + (2)(-i) + (3i)(1) + (3i)(-i) = 2 - 2i + 3i - 3i^2 = 2 + i - 3(-1) = 5 + i$." } ] } },
  
  // Numerical Methods (4)
  { topic: "Numerical Methods", title: "Newton-Raphson Method", question: "The Newton-Raphson iteration formula to find a root of $f(x)=0$ is:", options: [ { text: "$x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}$", is_correct: true }, { text: "$x_{n+1} = x_n + \\frac{f(x_n)}{f'(x_n)}$", is_correct: false }, { text: "$x_{n+1} = x_n - f(x_n) f'(x_n)$", is_correct: false }, { text: "$x_{n+1} = \\frac{x_n + f(x_n)}{2}$", is_correct: false } ], solution: { steps: [ { title: "Standard Formula", content: "Derived from the first-order Taylor expansion." } ] } },
  { topic: "Numerical Methods", title: "Trapezoidal Rule", question: "Using the Trapezoidal rule with one interval to approximate $\\int_0^2 x^2 dx$, the result is:", options: [ { text: "4", is_correct: true }, { text: "2.67", is_correct: false }, { text: "2", is_correct: false }, { text: "8", is_correct: false } ], solution: { steps: [ { title: "Trapezoidal Area", content: "$A = \\frac{b-a}{2} (f(a) + f(b)) = \\frac{2-0}{2} (0^2 + 2^2) = 1 \\times 4 = 4$." } ] } },
  { topic: "Numerical Methods", title: "Simpson's 1/3 Rule", question: "Simpson's 1/3 rule for numerical integration uses interpolating polynomials of what degree?", options: [ { text: "Second degree (parabolas)", is_correct: true }, { text: "First degree (straight lines)", is_correct: false }, { text: "Third degree (cubics)", is_correct: false }, { text: "Zero degree (constants)", is_correct: false } ], solution: { steps: [ { title: "Methodology", content: "Simpson's 1/3 rule fits a quadratic polynomial through three points." } ] } },
  { topic: "Numerical Methods", title: "Bisection Method", question: "The Bisection method for finding a root of $f(x)$ requires that the initial bracket $[a, b]$ satisfies:", options: [ { text: "$f(a) \\cdot f(b) < 0$", is_correct: true }, { text: "$f(a) \\cdot f(b) > 0$", is_correct: false }, { text: "$f(a) + f(b) = 0$", is_correct: false }, { text: "$f'(a) \\cdot f'(b) < 0$", is_correct: false } ], solution: { steps: [ { title: "Intermediate Value Theorem", content: "The function must change sign over the interval $[a, b]$." } ] } },
  
  // Probability (5)
  { topic: "Probability", title: "Independent Events", question: "If events $A$ and $B$ are independent, what is $P(A \\cap B)$?", options: [ { text: "$P(A) \\cdot P(B)$", is_correct: true }, { text: "$P(A) + P(B)$", is_correct: false }, { text: "$P(A) - P(B)$", is_correct: false }, { text: "$P(A|B)$", is_correct: false } ], solution: { steps: [ { title: "Definition of Independence", content: "By definition, the joint probability of independent events is the product of their marginal probabilities." } ] } },
  { topic: "Probability", title: "Mutually Exclusive Events", question: "If a single card is drawn from a deck, what is the probability it is both a Heart and a Spade?", options: [ { text: "0", is_correct: true }, { text: "1/52", is_correct: false }, { text: "1/4", is_correct: false }, { text: "1/2", is_correct: false } ], solution: { steps: [ { title: "Mutually Exclusive", content: "A card cannot be both a Heart and a Spade simultaneously." } ] } },
  { topic: "Probability", title: "Conditional Probability", question: "Given $P(A) = 0.5$, $P(B) = 0.4$, and $P(A \\cap B) = 0.2$, find $P(A|B)$.", options: [ { text: "0.5", is_correct: true }, { text: "0.2", is_correct: false }, { text: "0.4", is_correct: false }, { text: "0.8", is_correct: false } ], solution: { steps: [ { title: "Bayes Rule", content: "$P(A|B) = \\frac{P(A \\cap B)}{P(B)} = \\frac{0.2}{0.4} = 0.5$." } ] } },
  { topic: "Probability", title: "Combinations", question: "How many ways can a committee of 3 be chosen from a group of 5 people?", options: [ { text: "10", is_correct: true }, { text: "60", is_correct: false }, { text: "15", is_correct: false }, { text: "5", is_correct: false } ], solution: { steps: [ { title: "Calculate Combinations", content: "$C(5,3) = \\frac{5!}{3!(5-3)!} = \\frac{5 \\times 4}{2} = 10$." } ] } },
  { topic: "Probability", title: "Binomial Distribution", question: "In a binomial experiment with $n=3$ trials and success probability $p=0.5$, what is the probability of getting exactly 2 successes?", options: [ { text: "0.375", is_correct: true }, { text: "0.125", is_correct: false }, { text: "0.500", is_correct: false }, { text: "0.250", is_correct: false } ], solution: { steps: [ { title: "Binomial Formula", content: "$P(X=2) = \\binom{3}{2} (0.5)^2 (0.5)^1 = 3 \\times 0.25 \\times 0.5 = 0.375$." } ] } },
  
  // Statistics (3)
  { topic: "Statistics", title: "Sample Mean", question: "Find the sample mean of the dataset: 2, 4, 6, 8, 10.", options: [ { text: "6", is_correct: true }, { text: "5", is_correct: false }, { text: "7", is_correct: false }, { text: "8", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "$(2+4+6+8+10)/5 = 30/5 = 6$." } ] } },
  { topic: "Statistics", title: "Standard Deviation", question: "If the variance of a dataset is 16, what is its standard deviation?", options: [ { text: "4", is_correct: true }, { text: "8", is_correct: false }, { text: "256", is_correct: false }, { text: "16", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "Standard deviation is the square root of variance: $\\sqrt{16} = 4$." } ] } },
  { topic: "Statistics", title: "Median vs Mean", question: "In a positively (right) skewed distribution, how do the mean and median typically relate?", options: [ { text: "Mean > Median", is_correct: true }, { text: "Mean < Median", is_correct: false }, { text: "Mean = Median", is_correct: false }, { text: "Cannot be determined", is_correct: false } ], solution: { steps: [ { title: "Skewness", content: "In a right-skewed distribution, the long tail pulls the mean to the right of the median." } ] } }
];

const ethicsNew = [
  // Codes of Ethics (5)
  { topic: "Codes of Ethics", title: "NSPE Code Principle", question: "According to the NSPE Code of Ethics, engineers shall hold paramount the safety, health, and welfare of the:", options: [ { text: "Public", is_correct: true }, { text: "Client", is_correct: false }, { text: "Employer", is_correct: false }, { text: "Engineering profession", is_correct: false } ], solution: { steps: [ { title: "Fundamental Canon 1", content: "The paramount duty of all engineers is to the public." } ] } },
  { topic: "Codes of Ethics", title: "Area of Competence", question: "The NSPE Code states that engineers shall perform services only in the areas of their:", options: [ { text: "Competence", is_correct: true }, { text: "Interest", is_correct: false }, { text: "Financial benefit", is_correct: false }, { text: "Employer's request", is_correct: false } ], solution: { steps: [ { title: "Fundamental Canon 2", content: "Engineers must not accept assignments outside their education and experience." } ] } },
  { topic: "Codes of Ethics", title: "Public Statements", question: "Engineers shall issue public statements only in an objective and _____ manner.", options: [ { text: "Truthful", is_correct: true }, { text: "Persuasive", is_correct: false }, { text: "Profitable", is_correct: false }, { text: "Subjective", is_correct: false } ], solution: { steps: [ { title: "Fundamental Canon 3", content: "Objectivity and truthfulness are required in all public reports, statements, or testimony." } ] } },
  { topic: "Codes of Ethics", title: "Faithful Agents", question: "Engineers shall act for each employer or client as faithful agents or:", options: [ { text: "Trustees", is_correct: true }, { text: "Subcontractors", is_correct: false }, { text: "Advocates", is_correct: false }, { text: "Employees", is_correct: false } ], solution: { steps: [ { title: "Fundamental Canon 4", content: "Engineers must avoid conflicts of interest and act as faithful agents or trustees." } ] } },
  { topic: "Codes of Ethics", title: "Deceptive Acts", question: "According to the NSPE Code, engineers shall avoid _____ acts.", options: [ { text: "Deceptive", is_correct: true }, { text: "Charitable", is_correct: false }, { text: "Political", is_correct: false }, { text: "Administrative", is_correct: false } ], solution: { steps: [ { title: "Fundamental Canon 5", content: "Engineers shall avoid deceptive acts to protect the integrity of the profession." } ] } },
  
  // Intellectual Property (5)
  { topic: "Intellectual Property", title: "Patent Duration", question: "In the United States, a utility patent generally lasts for how many years from the filing date?", options: [ { text: "20 years", is_correct: true }, { text: "10 years", is_correct: false }, { text: "15 years", is_correct: false }, { text: "Life of the inventor plus 70 years", is_correct: false } ], solution: { steps: [ { title: "Patent Law", content: "Utility patents are granted for 20 years from the date of filing." } ] } },
  { topic: "Intellectual Property", title: "Copyright Subject Matter", question: "Which of the following can be protected by a copyright?", options: [ { text: "A software source code", is_correct: true }, { text: "A new mechanical invention", is_correct: false }, { text: "A company logo", is_correct: false }, { text: "A mathematical formula", is_correct: false } ], solution: { steps: [ { title: "Copyright Law", content: "Copyright protects original works of authorship, including written code." } ] } },
  { topic: "Intellectual Property", title: "Trademarks", question: "A trademark is primarily used to protect:", options: [ { text: "Brand names and logos identifying the source of goods", is_correct: true }, { text: "Novel manufacturing processes", is_correct: false }, { text: "Trade secrets", is_correct: false }, { text: "Literary works", is_correct: false } ], solution: { steps: [ { title: "Trademark Law", content: "Trademarks distinguish the goods/services of one enterprise from another." } ] } },
  { topic: "Intellectual Property", title: "Trade Secrets", question: "To maintain trade secret protection, a company must:", options: [ { text: "Take reasonable steps to keep the information confidential", is_correct: true }, { text: "File an application with the government", is_correct: false }, { text: "Publish the secret in a technical journal", is_correct: false }, { text: "Renew the status every 10 years", is_correct: false } ], solution: { steps: [ { title: "Trade Secret Law", content: "Protection relies entirely on the secret being kept reasonably confidential." } ] } },
  { topic: "Intellectual Property", title: "Non-Disclosure Agreements", question: "An NDA is a legal contract designed primarily to:", options: [ { text: "Protect confidential information and trade secrets", is_correct: true }, { text: "Transfer patent ownership", is_correct: false }, { text: "Grant copyright licenses", is_correct: false }, { text: "Prevent employees from joining competitors", is_correct: false } ], solution: { steps: [ { title: "NDA Purpose", content: "NDAs legally bind parties to maintain secrecy regarding shared information." } ] } },
  
  // Public Health and Safety (9)
  { topic: "Public Health and Safety", title: "Whistleblowing", question: "If an engineer discovers an unsafe practice that their employer refuses to fix, their ultimate ethical obligation is to:", options: [ { text: "Report it to the appropriate external regulatory authority", is_correct: true }, { text: "Resign silently", is_correct: false }, { text: "Fix it themselves secretly", is_correct: false }, { text: "Document it but take no action", is_correct: false } ], solution: { steps: [ { title: "Ethical Duty", content: "Paramount duty to the public requires whistleblowing if internal channels fail to address safety threats." } ] } },
  { topic: "Public Health and Safety", title: "Design Margins", question: "Using an appropriate Factor of Safety (FS) in a design is a direct application of the engineer's obligation to:", options: [ { text: "Public health and safety", is_correct: true }, { text: "Cost reduction", is_correct: false }, { text: "Employer profitability", is_correct: false }, { text: "Intellectual property", is_correct: false } ], solution: { steps: [ { title: "Safety in Design", content: "FS accounts for uncertainties to ensure structural integrity and public safety." } ] } },
  { topic: "Public Health and Safety", title: "Informing Clients", question: "If an engineer's professional judgment is overruled such that safety is endangered, they should:", options: [ { text: "Notify the client, employer, and other appropriate authorities", is_correct: true }, { text: "Accept the decision since the employer holds liability", is_correct: false }, { text: "Ask for a raise", is_correct: false }, { text: "Ignore the issue", is_correct: false } ], solution: { steps: [ { title: "Code of Ethics", content: "Engineers must alert relevant parties when their judgment is overruled in safety matters." } ] } },
  { topic: "Public Health and Safety", title: "Hazardous Materials", question: "When handling hazardous materials, the engineer must ensure compliance with:", options: [ { text: "All applicable local, state, and federal environmental regulations", is_correct: true }, { text: "Only internal company guidelines", is_correct: false }, { text: "Guidelines that minimize disposal costs", is_correct: false }, { text: "International voluntary standards only", is_correct: false } ], solution: { steps: [ { title: "Regulatory Compliance", content: "Legal compliance is mandatory for protecting public health." } ] } },
  { topic: "Public Health and Safety", title: "Risk Communication", question: "Engineers have a responsibility to communicate technical risks to the public in a manner that is:", options: [ { text: "Clear, understandable, and truthful", is_correct: true }, { text: "Highly technical and obscured", is_correct: false }, { text: "Alarmist to ensure attention", is_correct: false }, { text: "Vague to prevent panic", is_correct: false } ], solution: { steps: [ { title: "Risk Communication", content: "The public has a right to clear, objective information about risks." } ] } },
  { topic: "Public Health and Safety", title: "Signing and Sealing", question: "An engineer should sign and seal design documents only when:", options: [ { text: "They were prepared under their direct supervisory control and meet safety standards", is_correct: true }, { text: "They are paid for the project", is_correct: false }, { text: "The project manager requests it", is_correct: false }, { text: "They have read them quickly", is_correct: false } ], solution: { steps: [ { title: "Sealing Rules", content: "A seal implies personal responsibility and that the work was done under their direct control." } ] } },
  { topic: "Public Health and Safety", title: "Continuing Education", question: "Maintaining competence through continuing education relates to public safety because:", options: [ { text: "Outdated knowledge can lead to unsafe designs", is_correct: true }, { text: "It is required for promotions", is_correct: false }, { text: "It increases company profits", is_correct: false }, { text: "It lowers insurance premiums", is_correct: false } ], solution: { steps: [ { title: "Competence", content: "Engineering is dynamic; staying current is necessary to apply safe, modern practices." } ] } },
  { topic: "Public Health and Safety", title: "Conflict Resolution", question: "In a conflict between budget constraints and safety codes, the engineer must prioritize:", options: [ { text: "Safety codes", is_correct: true }, { text: "Budget constraints", is_correct: false }, { text: "Client requests", is_correct: false }, { text: "Project schedule", is_correct: false } ], solution: { steps: [ { title: "Priorities", content: "Safety is paramount and cannot be compromised for budget." } ] } },
  { topic: "Public Health and Safety", title: "Product Recalls", question: "If a released product is found to be defective and dangerous, the ethical engineering action is to:", options: [ { text: "Advocate for an immediate recall or safety warning", is_correct: true }, { text: "Cover it up to avoid lawsuits", is_correct: false }, { text: "Wait until a customer complains", is_correct: false }, { text: "Blame the manufacturing department", is_correct: false } ], solution: { steps: [ { title: "Corrective Action", content: "Protecting the public requires immediate corrective action for dangerous products." } ] } },

  // Public Health, Safety, and Welfare (4)
  { topic: "Public Health, Safety, and Welfare", title: "Sustainable Design", question: "Considering the environmental impact and sustainability of a project is an aspect of protecting the public:", options: [ { text: "Welfare", is_correct: true }, { text: "Intellectual property", is_correct: false }, { text: "Budget", is_correct: false }, { text: "Profit margin", is_correct: false } ], solution: { steps: [ { title: "Welfare Definition", content: "Public welfare encompasses long-term well-being, including environmental sustainability." } ] } },
  { topic: "Public Health, Safety, and Welfare", title: "Building Codes", question: "Building codes are primarily established by governments to:", options: [ { text: "Set minimum standards to protect public health, safety, and general welfare", is_correct: true }, { text: "Generate tax revenue", is_correct: false }, { text: "Standardize construction costs", is_correct: false }, { text: "Limit architectural creativity", is_correct: false } ], solution: { steps: [ { title: "Purpose of Codes", content: "Codes ensure buildings are safe for occupancy." } ] } },
  { topic: "Public Health, Safety, and Welfare", title: "ADA Compliance", question: "Complying with the Americans with Disabilities Act (ADA) in engineering design is an ethical obligation to ensure:", options: [ { text: "Equitable access and welfare for all members of the public", is_correct: true }, { text: "Structural integrity", is_correct: false }, { text: "Energy efficiency", is_correct: false }, { text: "Cost minimization", is_correct: false } ], solution: { steps: [ { title: "Welfare and Access", content: "Public welfare includes designing inclusive environments." } ] } },
  { topic: "Public Health, Safety, and Welfare", title: "Quality Assurance", question: "Rigorous Quality Assurance (QA) testing of a new bridge design protects public safety by:", options: [ { text: "Identifying potential failure points before construction", is_correct: true }, { text: "Reducing material costs", is_correct: false }, { text: "Speeding up the construction timeline", is_correct: false }, { text: "Circumventing regulations", is_correct: false } ], solution: { steps: [ { title: "QA Role", content: "QA ensures the design translates safely to reality." } ] } },
  
  // Societal Considerations (8)
  { topic: "Societal Considerations", title: "Environmental Justice", question: "Ensuring that a new industrial facility does not disproportionately harm a minority or low-income neighborhood is a principle of:", options: [ { text: "Environmental justice", is_correct: true }, { text: "Eminent domain", is_correct: false }, { text: "Zoning deregulation", is_correct: false }, { text: "Cost-benefit analysis", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Environmental justice deals with fair treatment regarding environmental regulations and impacts." } ] } },
  { topic: "Societal Considerations", title: "Technological Impact", question: "Engineers should seek to understand the societal impact of their work, meaning they must consider:", options: [ { text: "Both the intended benefits and potential unintended negative consequences", is_correct: true }, { text: "Only the immediate financial ROI", is_correct: false }, { text: "Only how it affects their employer", is_correct: false }, { text: "How to maximize resource consumption", is_correct: false } ], solution: { steps: [ { title: "Broad View", content: "Technology has wide-ranging impacts on society that must be weighed." } ] } },
  { topic: "Societal Considerations", title: "Community Engagement", question: "When proposing a large civil infrastructure project, holding public hearings is important for:", options: [ { text: "Gathering community feedback and addressing societal concerns", is_correct: true }, { text: "Bypassing environmental laws", is_correct: false }, { text: "Advertising the engineering firm", is_correct: false }, { text: "Dictating terms to the residents", is_correct: false } ], solution: { steps: [ { title: "Engagement", content: "Public hearings integrate societal considerations into engineering planning." } ] } },
  { topic: "Societal Considerations", title: "Global Context", question: "When designing a product for international markets, an ethical engineer should consider:", options: [ { text: "Local cultural norms, infrastructure limitations, and differing safety standards", is_correct: true }, { text: "Only the standards of their home country", is_correct: false }, { text: "How to bypass foreign tariffs", is_correct: false }, { text: "Ignoring local laws if they are less strict", is_correct: false } ], solution: { steps: [ { title: "Global Engineering", content: "Societal contexts vary globally and affect design suitability and safety." } ] } },
  { topic: "Societal Considerations", title: "Privacy in Tech", question: "In software engineering, protecting user data privacy is an ethical obligation tied to:", options: [ { text: "Societal considerations and public welfare", is_correct: true }, { text: "Hardware optimization", is_correct: false }, { text: "Reducing server costs", is_correct: false }, { text: "Agile development", is_correct: false } ], solution: { steps: [ { title: "Data Privacy", content: "Privacy is a fundamental societal right in the digital age." } ] } },
  { topic: "Societal Considerations", title: "Automation Impact", question: "When implementing automation that replaces human labor, a macro-level societal consideration is:", options: [ { text: "The displacement of workers and the need for retraining programs", is_correct: true }, { text: "The increased speed of the assembly line only", is_correct: false }, { text: "The reduction in coffee consumption at the plant", is_correct: false }, { text: "The physical color of the robots", is_correct: false } ], solution: { steps: [ { title: "Societal Impact", content: "Job displacement is a significant socio-economic effect of automation." } ] } },
  { topic: "Societal Considerations", title: "Life Cycle Assessment", question: "A Life Cycle Assessment (LCA) evaluates a product's environmental impact from 'cradle to grave', reflecting an engineer's commitment to:", options: [ { text: "Sustainable development and societal welfare", is_correct: true }, { text: "Short-term profitability", is_correct: false }, { text: "Planned obsolescence", is_correct: false }, { text: "Ignoring disposal costs", is_correct: false } ], solution: { steps: [ { title: "LCA Purpose", content: "LCA ensures engineers consider long-term environmental and societal burdens." } ] } },
  { topic: "Societal Considerations", title: "Eminent Domain", question: "The government's power to take private property for public use (like building a highway), provided just compensation is given, is called:", options: [ { text: "Eminent domain", is_correct: true }, { text: "Zoning", is_correct: false }, { text: "Easement", is_correct: false }, { text: "Gentrification", is_correct: false } ], solution: { steps: [ { title: "Legal Concept", content: "Eminent domain balances societal infrastructure needs against private property rights." } ] } }
];

const allNewQuestions = {
  "math": rotateAnswers(mathNew, 0),
  "ethics": rotateAnswers(ethicsNew, 0)
};

for (const [subj, newQs] of Object.entries(allNewQuestions)) {
  if (questionsObj[subj]) {
    questionsObj[subj].push(...newQs);
  } else {
    questionsObj[subj] = newQs;
  }
}

const updatedJson = JSON.stringify(questionsObj, null, 4);
const prefixContent = fileContent.substring(0, fileContent.indexOf('const QUESTIONS ='));
fs.writeFileSync('questions.js', prefixContent + 'const QUESTIONS = ' + updatedJson + ';\n', 'utf8');
console.log(`Successfully added gaps for math and ethics.`);
