const fs = require('fs');

let fileContent = fs.readFileSync('questions.js', 'utf8');
const match = fileContent.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
if (!match) {
  console.log("Could not find QUESTIONS");
  process.exit(1);
}
const questionsObj = JSON.parse(match[1]);

function rotateAnswers(questions, startIdx) {
  let count = startIdx;
  const labels = ["A", "B", "C", "D"];
  return questions.map(q => {
    let correctIdx = count % 4;
    count++;
    let originalCorrectText = q.options.find(o => o.is_correct).text;
    let incorrectTexts = q.options.filter(o => !o.is_correct).map(o => o.text);
    
    let newOpts = [];
    let incCount = 0;
    for (let i = 0; i < 4; i++) {
      if (i === correctIdx) {
        newOpts.push({ label: labels[i], text: originalCorrectText, is_correct: true });
      } else {
        newOpts.push({ label: labels[i], text: incorrectTexts[incCount++], is_correct: false });
      }
    }
    q.options = newOpts;
    q.solution.final_answer = labels[correctIdx];
    return q;
  });
}

const productionNew = [
  // Inventory Management (3)
  { topic: "Inventory Management", title: "Economic Order Quantity (EOQ)", question: "In the basic EOQ model, the optimal order quantity occurs when the annual ordering cost is equal to the:", options: [ { text: "Annual holding (carrying) cost", is_correct: true }, { text: "Annual setup cost", is_correct: false }, { text: "Unit purchasing cost", is_correct: false }, { text: "Shortage cost", is_correct: false } ], solution: { steps: [ { title: "EOQ Principle", content: "The total cost curve is minimized at the exact point where holding costs intersect ordering costs." } ] } },
  { topic: "Inventory Management", title: "Safety Stock", question: "The primary purpose of holding safety stock in an inventory system is to:", options: [ { text: "Buffer against demand variability and lead time uncertainty", is_correct: true }, { text: "Take advantage of bulk purchasing discounts", is_correct: false }, { text: "Reduce the number of orders placed per year", is_correct: false }, { text: "Minimize holding costs", is_correct: false } ], solution: { steps: [ { title: "Purpose", content: "Safety stock prevents stockouts during the lead time when demand exceeds expectations." } ] } },
  { topic: "Inventory Management", title: "ABC Classification", question: "In ABC inventory classification, 'A' items typically account for approximately:", options: [ { text: "15-20% of items and 70-80% of total annual value", is_correct: true }, { text: "50% of items and 50% of value", is_correct: false }, { text: "80% of items and 20% of value", is_correct: false }, { text: "100% of items and 100% of value", is_correct: false } ], solution: { steps: [ { title: "Pareto Principle", content: "ABC analysis is based on Pareto's 80/20 rule, prioritizing high-value items." } ] } },
  // Manufacturing Systems (5)
  { topic: "Manufacturing Systems", title: "Just-In-Time (JIT)", question: "Which of the following is a primary objective of a Just-In-Time (JIT) manufacturing system?", options: [ { text: "Elimination of all forms of waste, including excess inventory", is_correct: true }, { text: "Maximizing machine utilization by running large batch sizes", is_correct: false }, { text: "Stockpiling raw materials to prevent shortages", is_correct: false }, { text: "Increasing work-in-process (WIP)", is_correct: false } ], solution: { steps: [ { title: "JIT Philosophy", content: "JIT seeks to produce only what is needed, when it is needed, eliminating waste (muda)." } ] } },
  { topic: "Manufacturing Systems", title: "Cellular Manufacturing", question: "Cellular manufacturing groups machines and workers into 'cells' based on:", options: [ { text: "Part families requiring similar processing steps", is_correct: true }, { text: "The physical size of the machinery", is_correct: false }, { text: "The alphabetical order of the parts", is_correct: false }, { text: "The seniority of the operators", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Group Technology (GT) is used to identify part families for cellular layouts." } ] } },
  { topic: "Manufacturing Systems", title: "Flexible Manufacturing Systems (FMS)", question: "A Flexible Manufacturing System (FMS) is best characterized by its ability to:", options: [ { text: "Easily adapt to changes in product type and volume", is_correct: true }, { text: "Produce a single product in massive quantities", is_correct: false }, { text: "Operate entirely without electrical power", is_correct: false }, { text: "Ignore quality control limits", is_correct: false } ], solution: { steps: [ { title: "FMS Attributes", content: "FMS combines CNC machines, automated material handling, and computer control for high flexibility." } ] } },
  { topic: "Manufacturing Systems", title: "Pull vs Push Systems", question: "Kanban is a signaling tool primarily used to facilitate which type of production system?", options: [ { text: "Pull system", is_correct: true }, { text: "Push system", is_correct: false }, { text: "Batch processing", is_correct: false }, { text: "Mass production", is_correct: false } ], solution: { steps: [ { title: "Kanban", content: "Kanban cards signal upstream processes to produce parts only when downstream processes consume them (Pull)." } ] } },
  { topic: "Manufacturing Systems", title: "Lean Manufacturing", question: "In Lean terminology, 'Kaizen' refers to:", options: [ { text: "Continuous improvement", is_correct: true }, { text: "Mistake proofing", is_correct: false }, { text: "Visual management", is_correct: false }, { text: "Standardized work", is_correct: false } ], solution: { steps: [ { title: "Translation", content: "Kaizen means 'change for the better' or continuous, incremental improvement." } ] } },
  // Production Planning (2)
  { topic: "Production Planning", title: "Master Production Schedule (MPS)", question: "The Master Production Schedule (MPS) specifies:", options: [ { text: "The exact quantities of specific end items to be produced in specific time periods", is_correct: true }, { text: "The aggregate production rate for product families", is_correct: false }, { text: "The list of raw materials required", is_correct: false }, { text: "The layout of the factory floor", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "MPS translates the aggregate plan into specific, buildable product schedules." } ] } },
  { topic: "Production Planning", title: "Material Requirements Planning (MRP)", question: "Which of the following is an essential input for an MRP system?", options: [ { text: "Bill of Materials (BOM)", is_correct: true }, { text: "Employee vacation schedules", is_correct: false }, { text: "Marketing brochures", is_correct: false }, { text: "Competitor pricing", is_correct: false } ], solution: { steps: [ { title: "MRP Inputs", content: "MRP requires the MPS, Bill of Materials, and Inventory Records to calculate net requirements." } ] } }
];

const supplyChainNew = [
  // Facility Layout (3)
  { topic: "Facility Layout", title: "Process Layout", question: "A process layout (functional layout) is most appropriate for a manufacturing facility that produces:", options: [ { text: "A wide variety of products in low volumes", is_correct: true }, { text: "A single product in very high volumes", is_correct: false }, { text: "Continuous flow chemicals", is_correct: false }, { text: "A fixed-position massive product like a ship", is_correct: false } ], solution: { steps: [ { title: "Layout Types", content: "Process layouts group similar equipment together, accommodating varied routing paths." } ] } },
  { topic: "Facility Layout", title: "Product Layout", question: "An assembly line is a classic example of which type of facility layout?", options: [ { text: "Product layout", is_correct: true }, { text: "Process layout", is_correct: false }, { text: "Fixed-position layout", is_correct: false }, { text: "Cellular layout", is_correct: false } ], solution: { steps: [ { title: "Layout Types", content: "Product layouts arrange equipment sequentially according to the steps required to make a single product." } ] } },
  { topic: "Facility Layout", title: "Line Balancing", question: "The goal of assembly line balancing is to assign tasks to workstations such that:", options: [ { text: "Idle time is minimized and workloads are equalized", is_correct: true }, { text: "Cycle time is maximized", is_correct: false }, { text: "Distance traveled is maximized", is_correct: false }, { text: "The number of workstations is maximized", is_correct: false } ], solution: { steps: [ { title: "Balancing Objective", content: "Balancing smooths the flow and reduces bottlenecks." } ] } },
  // Logistics (4)
  { topic: "Logistics", title: "Cross-Docking", question: "A logistics strategy where incoming shipments are unloaded from inbound trailers and loaded directly onto outbound trailers with little to no storage time is called:", options: [ { text: "Cross-docking", is_correct: true }, { text: "Warehousing", is_correct: false }, { text: "Drop shipping", is_correct: false }, { text: "Reverse logistics", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Cross-docking eliminates the need for holding inventory in the distribution center." } ] } },
  { topic: "Logistics", title: "Reverse Logistics", question: "The process of moving goods from their typical final destination back to the manufacturer for the purpose of capturing value or proper disposal is known as:", options: [ { text: "Reverse logistics", is_correct: true }, { text: "Inbound logistics", is_correct: false }, { text: "Third-party logistics", is_correct: false }, { text: "Outbound logistics", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Includes returns, recycling, and remanufacturing." } ] } },
  { topic: "Logistics", title: "Transportation Modes", question: "Which mode of transportation generally offers the lowest cost per ton-mile for transporting massive, bulk commodities over long land distances?", options: [ { text: "Rail", is_correct: true }, { text: "Air", is_correct: false }, { text: "Truck", is_correct: false }, { text: "Pipeline", is_correct: false } ], solution: { steps: [ { title: "Mode Comparison", content: "Rail and water are cheapest for bulk freight. (Pipeline is specifically for liquids/gases)." } ] } },
  { topic: "Logistics", title: "Third-Party Logistics (3PL)", question: "When a company outsources its transportation, warehousing, and related logistics activities to an external provider, that provider is referred to as a:", options: [ { text: "3PL (Third-Party Logistics provider)", is_correct: true }, { text: "OEM (Original Equipment Manufacturer)", is_correct: false }, { text: "Tier 1 supplier", is_correct: false }, { text: "Retailer", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "3PLs specialize in integrated operation, warehousing, and transportation services." } ] } },
  // Supply Chain Management (3)
  { topic: "Supply Chain Management", title: "Bullwhip Effect", question: "The phenomenon where small fluctuations in retail demand cause progressively larger fluctuations in demand further up the supply chain is known as the:", options: [ { text: "Bullwhip effect", is_correct: true }, { text: "Butterfly effect", is_correct: false }, { text: "Ripple effect", is_correct: false }, { text: "Halo effect", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "The bullwhip effect is caused by information delays, batching, and forecasting errors." } ] } },
  { topic: "Supply Chain Management", title: "Vertical Integration", question: "A manufacturing company that acquires its supplier of raw materials is engaging in:", options: [ { text: "Backward vertical integration", is_correct: true }, { text: "Forward vertical integration", is_correct: false }, { text: "Horizontal integration", is_correct: false }, { text: "Outsourcing", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Backward integration means taking control of supply chain elements upstream." } ] } },
  { topic: "Supply Chain Management", title: "Vendor Managed Inventory", question: "Vendor-Managed Inventory (VMI) is an approach where the:", options: [ { text: "Supplier is responsible for monitoring and replenishing the buyer's inventory", is_correct: true }, { text: "Buyer dictates exactly when the supplier must manufacture parts", is_correct: false }, { text: "Inventory is held by a third-party warehouse", is_correct: false }, { text: "Supplier only produces goods after a customer buys them", is_correct: false } ], solution: { steps: [ { title: "VMI Strategy", content: "VMI shifts the responsibility of inventory tracking and replenishment to the supplier." } ] } }
];

const ergonomicsNew = [
  // Anthropometry (8)
  { topic: "Anthropometry", title: "Definition of Anthropometry", question: "Anthropometry is the scientific study of the:", options: [ { text: "Measurements and proportions of the human body", is_correct: true }, { text: "Motion of human joints", is_correct: false }, { text: "Cognitive capabilities of humans", is_correct: false }, { text: "Social interactions in the workplace", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Derived from Greek 'anthropos' (man) and 'metron' (measure)." } ] } },
  { topic: "Anthropometry", title: "Design for the Extremes", question: "When designing a doorway height, which anthropometric design principle should be applied?", options: [ { text: "Design for the extreme (95th or 99th percentile male)", is_correct: true }, { text: "Design for the average", is_correct: false }, { text: "Design for adjustability", is_correct: false }, { text: "Design for the 5th percentile female", is_correct: false } ], solution: { steps: [ { title: "Clearance Principle", content: "Clearances should accommodate the largest individuals." } ] } },
  { topic: "Anthropometry", title: "Design for the Extremes (Reach)", question: "When designing the placement of an emergency stop button, the reach distance should accommodate the:", options: [ { text: "5th percentile female (smallest reach)", is_correct: true }, { text: "95th percentile male", is_correct: false }, { text: "50th percentile person", is_correct: false }, { text: "Average user", is_correct: false } ], solution: { steps: [ { title: "Reach Principle", content: "Reach envelopes must ensure the smallest users can easily reach critical controls." } ] } },
  { topic: "Anthropometry", title: "Design for Adjustability", question: "Office chairs are typically designed using which anthropometric principle to accommodate a wide range of users?", options: [ { text: "Design for adjustability (5th to 95th percentiles)", is_correct: true }, { text: "Design for the average", is_correct: false }, { text: "Design for the extreme", is_correct: false }, { text: "Design for the 1st percentile", is_correct: false } ], solution: { steps: [ { title: "Adjustability", content: "Allows users to change seat height, armrests, etc. to fit their specific dimensions." } ] } },
  { topic: "Anthropometry", title: "Static vs Dynamic Anthropometry", question: "Measurements taken while the body is engaged in a physical activity (e.g., reaching, bending) are called:", options: [ { text: "Dynamic (functional) anthropometry", is_correct: true }, { text: "Static (structural) anthropometry", is_correct: false }, { text: "Biomechanics", is_correct: false }, { text: "Kinesiology", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Dynamic anthropometry accounts for the movement of joints and body parts." } ] } },
  { topic: "Anthropometry", title: "Z-score in Anthropometry", question: "To find the 95th percentile value of a normally distributed anthropometric dimension, one would add to the mean the standard deviation multiplied by a Z-score of approximately:", options: [ { text: "1.645", is_correct: true }, { text: "1.96", is_correct: false }, { text: "1.00", is_correct: false }, { text: "2.58", is_correct: false } ], solution: { steps: [ { title: "Z-Score", content: "The one-tailed Z-score for the 95th percentile is 1.645." } ] } },
  { topic: "Anthropometry", title: "Fallacy of the Average", question: "Designing a workspace based strictly on 'average' human dimensions (the 50th percentile) is generally considered:", options: [ { text: "Poor practice because it fits almost no one perfectly", is_correct: true }, { text: "The best practice for reducing costs", is_correct: false }, { text: "Acceptable for safety equipment", is_correct: false }, { text: "Required by OSHA", is_correct: false } ], solution: { steps: [ { title: "Principle", content: "A person might be average in height but not in arm length; designing for the average usually excludes the extremes." } ] } },
  { topic: "Anthropometry", title: "Popliteal Height", question: "To determine the appropriate height of a chair seat to prevent pressure on the back of the thighs, which anthropometric measurement is most critical?", options: [ { text: "Popliteal height", is_correct: true }, { text: "Sitting elbow height", is_correct: false }, { text: "Stature", is_correct: false }, { text: "Knee height", is_correct: false } ], solution: { steps: [ { title: "Anatomy", content: "Popliteal height is the distance from the floor to the crease behind the knee." } ] } },
  // Ergonomics (6)
  { topic: "Ergonomics", title: "Ergonomics Definition", question: "Ergonomics (or Human Factors) is formally defined as the study of:", options: [ { text: "The interaction between humans and elements of a system to optimize well-being and system performance", is_correct: true }, { text: "The psychological behavior of consumers", is_correct: false }, { text: "The economic impact of occupational injuries", is_correct: false }, { text: "The automation of manual labor tasks", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "IEA definition focuses on fitting the task/environment to the human." } ] } },
  { topic: "Ergonomics", title: "Cumulative Trauma Disorders", question: "Carpal Tunnel Syndrome is an example of a(n):", options: [ { text: "Cumulative Trauma Disorder (CTD) / Repetitive Strain Injury (RSI)", is_correct: true }, { text: "Acute occupational injury", is_correct: false }, { text: "Psychosocial stress disorder", is_correct: false }, { text: "Systemic infectious disease", is_correct: false } ], solution: { steps: [ { title: "Classification", content: "CTDs result from repeated micro-traumas over a long period." } ] } },
  { topic: "Ergonomics", title: "NIOSH Lifting Equation", question: "The NIOSH lifting equation provides a Recommended Weight Limit (RWL). A Lifting Index (LI) greater than what value indicates an increased risk of lower back injury?", options: [ { text: "1.0", is_correct: true }, { text: "0.5", is_correct: false }, { text: "5.0", is_correct: false }, { text: "10.0", is_correct: false } ], solution: { steps: [ { title: "Lifting Index", content: "$LI = \\text{Actual Weight} / \\text{RWL}$. Values > 1 indicate hazard." } ] } },
  { topic: "Ergonomics", title: "Visual Displays", question: "In ergonomic design of visual displays, the most important information should be placed:", options: [ { text: "In the center of the operator's normal line of sight", is_correct: true }, { text: "In the peripheral vision areas", is_correct: false }, { text: "At the very top of the panel", is_correct: false }, { text: "At the bottom right corner", is_correct: false } ], solution: { steps: [ { title: "Display Design", content: "Critical information must be immediately visible without head/eye movement." } ] } },
  { topic: "Ergonomics", title: "Controls Coding", question: "Using different shapes for control knobs (e.g., in an airplane cockpit) so they can be identified by touch is known as:", options: [ { text: "Shape coding", is_correct: true }, { text: "Color coding", is_correct: false }, { text: "Size coding", is_correct: false }, { text: "Location coding", is_correct: false } ], solution: { steps: [ { title: "Coding Mechanisms", content: "Shape coding allows tactile identification without looking." } ] } },
  { topic: "Ergonomics", title: "Illumination", question: "The recommended illumination level (in lux or foot-candles) for a workstation depends primarily on the:", options: [ { text: "Visual complexity and detail of the task being performed", is_correct: true }, { text: "Time of day", is_correct: false }, { text: "Age of the building", is_correct: false }, { text: "Noise level in the room", is_correct: false } ], solution: { steps: [ { title: "Lighting Ergonomics", content: "Fine, detailed work requires much higher illumination than general tasks." } ] } },
  // Human Factors (4)
  { topic: "Human Factors", title: "Vigilance Decrement", question: "In human factors, the decline in an operator's ability to detect rare signals or anomalies over a long period of monitoring is known as:", options: [ { text: "Vigilance decrement", is_correct: true }, { text: "Information overload", is_correct: false }, { text: "Sensory adaptation", is_correct: false }, { text: "Cognitive dissonance", is_correct: false } ], solution: { steps: [ { title: "Cognitive Limitations", content: "Humans are poor at maintaining attention on rare events for extended periods." } ] } },
  { topic: "Human Factors", title: "Stimulus-Response Compatibility", question: "If turning a steering wheel to the right makes a vehicle turn right, this system exhibits high:", options: [ { text: "Stimulus-response compatibility", is_correct: true }, { text: "Fitts's Law accuracy", is_correct: false }, { text: "Hick-Hyman complexity", is_correct: false }, { text: "Anthropometric fit", is_correct: false } ], solution: { steps: [ { title: "Compatibility", content: "Natural or expected relationships between controls and responses reduce errors." } ] } },
  { topic: "Human Factors", title: "Fitts's Law", question: "Fitts's Law models human movement time as a function of:", options: [ { text: "The distance to the target and the width (size) of the target", is_correct: true }, { text: "The weight of the object being moved", is_correct: false }, { text: "The number of alternative choices", is_correct: false }, { text: "The age of the operator", is_correct: false } ], solution: { steps: [ { title: "Fitts's Law", content: "Movement Time (MT) increases with distance and decreases with target size." } ] } },
  { topic: "Human Factors", title: "Hick's Law", question: "Hick's Law states that a person's reaction time increases logarithmically as the:", options: [ { text: "Number of stimulus-response alternatives increases", is_correct: true }, { text: "Distance to the target increases", is_correct: false }, { text: "Noise level in the environment increases", is_correct: false }, { text: "Duration of the shift increases", is_correct: false } ], solution: { steps: [ { title: "Hick's Law", content: "More choices = longer decision time." } ] } },
  // Safety (6)
  { topic: "Safety", title: "Hierarchy of Controls", question: "According to the OSHA/NIOSH Hierarchy of Controls, which is the most effective method for controlling a hazard?", options: [ { text: "Elimination of the hazard", is_correct: true }, { text: "Engineering controls", is_correct: false }, { text: "Administrative controls", is_correct: false }, { text: "Personal Protective Equipment (PPE)", is_correct: false } ], solution: { steps: [ { title: "Hierarchy", content: "Elimination > Substitution > Engineering > Administrative > PPE." } ] } },
  { topic: "Safety", title: "Hierarchy of Controls (Least Effective)", question: "In the safety Hierarchy of Controls, what is considered the last line of defense (least effective)?", options: [ { text: "Personal Protective Equipment (PPE)", is_correct: true }, { text: "Substitution", is_correct: false }, { text: "Engineering Controls", is_correct: false }, { text: "Administrative Controls", is_correct: false } ], solution: { steps: [ { title: "PPE", content: "PPE relies entirely on human compliance and does not remove the hazard." } ] } },
  { topic: "Safety", title: "OSHA Recordable Incident Rate", question: "The OSHA Total Recordable Incident Rate (TRIR) is standardized based on the number of incidents per:", options: [ { text: "100 full-time employees working one year (200,000 hours)", is_correct: true }, { text: "1,000 employees per month", is_correct: false }, { text: "1,000,000 hours worked", is_correct: false }, { text: "10,000 hours worked", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "TRIR = (Number of incidents * 200,000) / Total hours worked." } ] } },
  { topic: "Safety", title: "Lockout/Tagout (LOTO)", question: "The primary purpose of a Lockout/Tagout (LOTO) procedure is to:", options: [ { text: "Prevent the unexpected startup or release of stored energy during equipment maintenance", is_correct: true }, { text: "Prevent unauthorized personnel from entering the facility", is_correct: false }, { text: "Tag defective products on the assembly line", is_correct: false }, { text: "Lock the building doors at the end of a shift", is_correct: false } ], solution: { steps: [ { title: "LOTO", content: "Critical safety procedure to isolate energy sources (electrical, hydraulic, mechanical)." } ] } },
  { topic: "Safety", title: "Fault Tree Analysis", question: "Fault Tree Analysis (FTA) is a top-down deductive safety analysis method that uses:", options: [ { text: "Boolean logic gates to model how component failures lead to a specific top-level event", is_correct: true }, { text: "Statistical process control charts to identify defects", is_correct: false }, { text: "Ergonomic checklists to evaluate posture", is_correct: false }, { text: "Time studies to measure worker efficiency", is_correct: false } ], solution: { steps: [ { title: "FTA", content: "Starts with the undesired event and finds combinations of root causes." } ] } },
  { topic: "Safety", title: "Job Hazard Analysis", question: "A Job Hazard Analysis (JHA) focuses on the relationship between:", options: [ { text: "The worker, the task, the tools, and the work environment", is_correct: true }, { text: "Management, union representatives, and OSHA", is_correct: false }, { text: "Raw material suppliers and customers", is_correct: false }, { text: "The engineering department and accounting", is_correct: false } ], solution: { steps: [ { title: "JHA Scope", content: "Breaks a job into steps to identify hazards and recommend safe procedures." } ] } },
  // Workstation Design (6)
  { topic: "Workstation Design", title: "Normal vs Maximum Reach", question: "In workstation design, the area that can be reached with a sweep of the forearm while the upper arm hangs naturally at the side is the:", options: [ { text: "Normal reach area", is_correct: true }, { text: "Maximum reach area", is_correct: false }, { text: "Optimal visual zone", is_correct: false }, { text: "Blind spot", is_correct: false } ], solution: { steps: [ { title: "Definitions", content: "Maximum reach requires extending the full arm." } ] } },
  { topic: "Workstation Design", title: "Work Surface Height (Precision)", question: "For fine, precision assembly work, the optimal work surface height is typically:", options: [ { text: "Above elbow height to allow the worker to see closely", is_correct: true }, { text: "Exactly at elbow height", is_correct: false }, { text: "Slightly below elbow height", is_correct: false }, { text: "At waist height", is_correct: false } ], solution: { steps: [ { title: "Height Rules", content: "Heavy work = below elbow. Light work = at elbow. Precision work = above elbow." } ] } },
  { topic: "Workstation Design", title: "Work Surface Height (Heavy)", question: "For heavy manual work requiring downward force, the optimal work surface height is:", options: [ { text: "Below elbow height", is_correct: true }, { text: "At elbow height", is_correct: false }, { text: "Above elbow height", is_correct: false }, { text: "At shoulder height", is_correct: false } ], solution: { steps: [ { title: "Height Rules", content: "Lower surfaces allow workers to apply body weight for force." } ] } },
  { topic: "Workstation Design", title: "Anti-Fatigue Mats", question: "The primary ergonomic benefit of placing anti-fatigue mats at a standing workstation is to:", options: [ { text: "Promote subtle muscle movements that enhance blood flow and reduce lower limb fatigue", is_correct: true }, { text: "Insulate the worker from electrical shocks", is_correct: false }, { text: "Prevent slip-and-fall accidents", is_correct: false }, { text: "Absorb spilled liquids", is_correct: false } ], solution: { steps: [ { title: "Ergonomics", content: "Standing on hard concrete causes blood pooling; mats encourage micro-movements." } ] } },
  { topic: "Workstation Design", title: "Seated vs Standing", question: "A seated workstation is generally preferred over a standing workstation when:", options: [ { text: "The task involves fine motor control and long durations without heavy lifting", is_correct: true }, { text: "The task requires moving heavy items frequently", is_correct: false }, { text: "The worker needs to reach areas beyond their maximum arm length frequently", is_correct: false }, { text: "The task involves strong downward forces", is_correct: false } ], solution: { steps: [ { title: "Posture Selection", content: "Sitting stabilizes the body for precision but limits reach and force." } ] } },
  { topic: "Workstation Design", title: "Clearance for Legs", question: "When designing a seated workstation, sufficient clearance must be provided under the desk to accommodate the:", options: [ { text: "Knees and feet of the 95th percentile male", is_correct: true }, { text: "Knees of the 5th percentile female", is_correct: false }, { text: "Arms of the 50th percentile person", is_correct: false }, { text: "Only the chair's wheels", is_correct: false } ], solution: { steps: [ { title: "Clearance", content: "Clearance dimensions always design for the largest individuals." } ] } }
];

const workDesignNew = [
  // Methods Engineering (2)
  { topic: "Methods Engineering", title: "Therbligs", question: "In motion study, fundamental hand motions like 'Grasp', 'Reach', and 'Position' are called:", options: [ { text: "Therbligs", is_correct: true }, { text: "Gilbreths", is_correct: false }, { text: "Micro-motions", is_correct: false }, { text: "Standard elements", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Named by Frank and Lillian Gilbreth (Gilbreth spelled backward, roughly)." } ] } },
  { topic: "Methods Engineering", title: "Principles of Motion Economy", question: "Which of the following is a key Principle of Motion Economy?", options: [ { text: "Both hands should begin and end their motions at the same time", is_correct: true }, { text: "Work should be done with one hand while the other rests", is_correct: false }, { text: "Tools should be kept in random locations to encourage alertness", is_correct: false }, { text: "Movements should involve the entire body rather than just the fingers", is_correct: false } ], solution: { steps: [ { title: "Motion Economy", content: "Symmetrical, simultaneous hand movements reduce fatigue and increase speed." } ] } },
  // Time Study (4)
  { topic: "Time Study", title: "Standard Time Calculation", question: "Standard time is calculated by adding which of the following to the Normal Time?", options: [ { text: "Allowances (PFD - Personal, Fatigue, Delay)", is_correct: true }, { text: "Performance Rating", is_correct: false }, { text: "Observed Time", is_correct: false }, { text: "Machine Time", is_correct: false } ], solution: { steps: [ { title: "Formula", content: "$Standard Time = Normal Time + Allowances$, where $Normal Time = Observed Time \\times Rating$." } ] } },
  { topic: "Time Study", title: "Performance Rating", question: "During a time study, the analyst judges the worker's pace relative to a standard pace. This process is called:", options: [ { text: "Performance rating (or leveling)", is_correct: true }, { text: "Allowance calculation", is_correct: false }, { text: "Work sampling", is_correct: false }, { text: "Element breakdown", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Adjusts the observed time to what a trained, average worker would achieve." } ] } },
  { topic: "Time Study", title: "Observed Time to Normal Time", question: "If the average observed time for a task is 2.0 minutes and the worker was rated at 110%, what is the Normal Time?", options: [ { text: "2.2 minutes", is_correct: true }, { text: "1.82 minutes", is_correct: false }, { text: "2.0 minutes", is_correct: false }, { text: "2.5 minutes", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "$NT = OT \\times Rating = 2.0 \\times 1.10 = 2.2$ minutes." } ] } },
  { topic: "Time Study", title: "Snapback vs Continuous Timing", question: "In a stopwatch time study, returning the watch to zero at the end of each work element is called the:", options: [ { text: "Snapback method", is_correct: true }, { text: "Continuous method", is_correct: false }, { text: "Work sampling method", is_correct: false }, { text: "Predetermined time method", is_correct: false } ], solution: { steps: [ { title: "Methodology", content: "Continuous timing keeps the watch running; snapback resets it." } ] } },
  // Work Measurement (4)
  { topic: "Work Measurement", title: "Work Sampling", question: "A technique based on making random observations of workers to determine the proportion of time spent on various activities is called:", options: [ { text: "Work sampling", is_correct: true }, { text: "Time study", is_correct: false }, { text: "Predetermined motion time systems (PMTS)", is_correct: false }, { text: "Methods-time measurement (MTM)", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "Uses statistics to estimate percentages without continuous timing." } ] } },
  { topic: "Work Measurement", title: "PMTS Systems", question: "Methods-Time Measurement (MTM) and MOST are examples of:", options: [ { text: "Predetermined Motion Time Systems (PMTS)", is_correct: true }, { text: "Direct stopwatch time studies", is_correct: false }, { text: "Physiological fatigue tests", is_correct: false }, { text: "Inventory control algorithms", is_correct: false } ], solution: { steps: [ { title: "Classification", content: "PMTS assigns standard time values to basic micro-motions from a database." } ] } },
  { topic: "Work Measurement", title: "Work Sampling Accuracy", question: "In work sampling, the number of observations required to achieve a desired confidence level depends primarily on:", options: [ { text: "The estimated proportion of time spent on the activity ($p$)", is_correct: true }, { text: "The performance rating of the worker", is_correct: false }, { text: "The time of day the study is conducted", is_correct: false }, { text: "The physical weight of the parts", is_correct: false } ], solution: { steps: [ { title: "Statistics", content: "Sample size $N = \\frac{Z^2 p(1-p)}{e^2}$." } ] } },
  { topic: "Work Measurement", title: "Learning Curve Effect", question: "The learning curve theory assumes that as the cumulative quantity produced doubles, the time required to produce one unit:", options: [ { text: "Decreases by a constant percentage", is_correct: true }, { text: "Increases exponentially", is_correct: false }, { text: "Drops to zero", is_correct: false }, { text: "Remains constant", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "E.g., an 80% learning curve means the 2nd unit takes 80% of the 1st, 4th takes 80% of the 2nd." } ] } }
];

const qualityNew = [
  // Quality Management (1)
  { topic: "Quality Management", title: "Six Sigma Goal", question: "The primary statistical goal of a Six Sigma quality program is to reduce process variation so that there are no more than:", options: [ { text: "3.4 defects per million opportunities (DPMO)", is_correct: true }, { text: "1 defect per thousand opportunities", is_correct: false }, { text: "6 defects per million opportunities", is_correct: false }, { text: "Zero defects total", is_correct: false } ], solution: { steps: [ { title: "Six Sigma", content: "Accounting for a 1.5 sigma shift, the defect rate beyond 6 sigma limits is 3.4 DPMO." } ] } },
  // Reliability (5)
  { topic: "Reliability", title: "Series System Reliability", question: "If a system consists of two independent components in series, with reliabilities $R_1 = 0.9$ and $R_2 = 0.8$, the system reliability is:", options: [ { text: "0.72", is_correct: true }, { text: "0.98", is_correct: false }, { text: "0.85", is_correct: false }, { text: "1.70", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "$R_{sys} = R_1 \\times R_2 = 0.9 \\times 0.8 = 0.72$." } ] } },
  { topic: "Reliability", title: "Parallel System Reliability", question: "For two identical components in parallel (redundancy) each with reliability $R=0.9$, what is the overall system reliability?", options: [ { text: "0.99", is_correct: true }, { text: "0.81", is_correct: false }, { text: "0.90", is_correct: false }, { text: "1.80", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "$R_{sys} = 1 - (1-R)(1-R) = 1 - (0.1)(0.1) = 1 - 0.01 = 0.99$." } ] } },
  { topic: "Reliability", title: "MTBF", question: "If a component has a constant failure rate $\\lambda$ of $0.002$ failures per hour, what is its Mean Time Between Failures (MTBF)?", options: [ { text: "500 hours", is_correct: true }, { text: "200 hours", is_correct: false }, { text: "0.002 hours", is_correct: false }, { text: "1000 hours", is_correct: false } ], solution: { steps: [ { title: "Formula", content: "$MTBF = 1 / \\lambda = 1 / 0.002 = 500$." } ] } },
  { topic: "Reliability", title: "Exponential Reliability Function", question: "For a constant failure rate $\\lambda$, the reliability function $R(t)$ is given by:", options: [ { text: "$e^{-\\lambda t}$", is_correct: true }, { text: "$1 - e^{-\\lambda t}$", is_correct: false }, { text: "$\\lambda e^{-\\lambda t}$", is_correct: false }, { text: "$\\frac{1}{\\lambda t}$", is_correct: false } ], solution: { steps: [ { title: "Function", content: "The probability of surviving past time $t$ is $e^{-\\lambda t}$." } ] } },
  { topic: "Reliability", title: "Bathtub Curve", question: "The 'bathtub curve' models failure rates over the lifecycle of a product. The middle, flat portion of the curve represents:", options: [ { text: "Constant failure rate (random failures)", is_correct: true }, { text: "Infant mortality (early failures)", is_correct: false }, { text: "Wear-out failures", is_correct: false }, { text: "Zero failures", is_correct: false } ], solution: { steps: [ { title: "Theory", content: "Starts with high early failure, levels out to constant random failure, then rises at wear-out." } ] } },
  // Statistical Process Control (4)
  { topic: "Statistical Process Control", title: "Control Limits", question: "In a Shewhart control chart, the Upper and Lower Control Limits (UCL and LCL) are typically set at how many standard deviations from the process mean?", options: [ { text: "3", is_correct: true }, { text: "1", is_correct: false }, { text: "2", is_correct: false }, { text: "6", is_correct: false } ], solution: { steps: [ { title: "Standard Practice", content: "$\u00b1 3\\sigma$ limits capture 99.73% of natural variation." } ] } },
  { topic: "Statistical Process Control", title: "Common vs Special Cause Variation", question: "Variation that is inherent to the process design and cannot be traced to a single, assignable cause is known as:", options: [ { text: "Common cause variation", is_correct: true }, { text: "Special cause variation", is_correct: false }, { text: "Assignable cause variation", is_correct: false }, { text: "Out-of-control variation", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "Also known as random or systemic variation." } ] } },
  { topic: "Statistical Process Control", title: "X-bar Chart", question: "An X-bar ($\\bar{X}$) chart is used primarily to monitor the:", options: [ { text: "Process mean (central tendency)", is_correct: true }, { text: "Process variability (dispersion)", is_correct: false }, { text: "Number of defects per unit", is_correct: false }, { text: "Proportion of defective items", is_correct: false } ], solution: { steps: [ { title: "Chart Types", content: "$\\bar{X}$ tracks the mean, while R or S charts track dispersion." } ] } },
  { topic: "Statistical Process Control", title: "Process Capability Index (Cpk)", question: "A process capability index ($C_{pk}$) of 1.0 indicates that:", options: [ { text: "The process mean is exactly 3 standard deviations away from the nearest specification limit", is_correct: true }, { text: "The process is producing 100% defective parts", is_correct: false }, { text: "The process is out of control", is_correct: false }, { text: "The process meets Six Sigma standards", is_correct: false } ], solution: { steps: [ { title: "Definition", content: "$C_{pk} = \\min(\\frac{USL-\\mu}{3\\sigma}, \\frac{\\mu-LSL}{3\\sigma})$. If $C_{pk}=1$, the mean is $3\\sigma$ from a limit." } ] } }
];

const systemsNew = [
  // Systems Analysis (4)
  { topic: "Systems Analysis", title: "Systems Thinking", question: "Systems thinking is primarily characterized by focusing on:", options: [ { text: "How constituent parts interrelate and behave as a whole within the context of larger systems", is_correct: true }, { text: "Breaking down a problem into isolated, unrelated components", is_correct: false }, { text: "Only the financial inputs and outputs of a project", is_correct: false }, { text: "The software programming of a specific module", is_correct: false } ], solution: { steps: [ { title: "Philosophy", content: "Systems thinking looks at the 'big picture' and holism rather than reductionism." } ] } },
  { topic: "Systems Analysis", title: "System Boundary", question: "In systems engineering, the conceptual line that separates the system under study from its environment is called the:", options: [ { text: "System boundary", is_correct: true }, { text: "Subsystem", is_correct: false }, { text: "Interface", is_correct: false }, { text: "Feedback loop", is_correct: false } ], solution: { steps: [ { title: "Terminology", content: "The boundary defines what is inside the system and what is part of the external environment." } ] } },
  { topic: "Systems Analysis", title: "Feedback Loops", question: "A system behavior where the output of the system is routed back as an input, causing a dampening or stabilizing effect, is known as:", options: [ { text: "Negative feedback", is_correct: true }, { text: "Positive feedback", is_correct: false }, { text: "Feedforward", is_correct: false }, { text: "Open-loop control", is_correct: false } ], solution: { steps: [ { title: "Control Theory", content: "Negative feedback counters changes, promoting stability (e.g., a thermostat)." } ] } },
  { topic: "Systems Analysis", title: "Emergence", question: "The concept that a system possesses properties or behaviors that its individual components do not possess on their own is known as:", options: [ { text: "Emergence", is_correct: true }, { text: "Reductionism", is_correct: false }, { text: "Sub-optimization", is_correct: false }, { text: "Entropy", is_correct: false } ], solution: { steps: [ { title: "Systems Concept", content: "Emergent properties (like consciousness from neurons) appear only when parts interact." } ] } },
  // Systems Design (3)
  { topic: "Systems Design", title: "Systems Development Life Cycle (SDLC)", question: "In the traditional V-model of systems engineering, the left side of the 'V' represents:", options: [ { text: "Concept, requirements, and design (decomposition)", is_correct: true }, { text: "Integration, testing, and verification (recomposition)", is_correct: false }, { text: "Operations and maintenance", is_correct: false }, { text: "Disposal and retirement", is_correct: false } ], solution: { steps: [ { title: "V-Model", content: "The left side goes down into detailed design; the right side goes up through integration and testing." } ] } },
  { topic: "Systems Design", title: "Requirements Traceability", question: "The ability to follow a system requirement forwards to its implementation and backwards to its origin is called:", options: [ { text: "Traceability", is_correct: true }, { text: "Verification", is_correct: false }, { text: "Validation", is_correct: false }, { text: "Configuration management", is_correct: false } ], solution: { steps: [ { title: "Requirements Engineering", content: "Traceability ensures all requirements are met and no unnecessary features are added." } ] } },
  { topic: "Systems Design", title: "Trade Studies", question: "An objective evaluation of alternative design solutions against defined criteria (like cost, performance, and risk) is called a:", options: [ { text: "Trade study", is_correct: true }, { text: "Feasibility study", is_correct: false }, { text: "Post-mortem analysis", is_correct: false }, { text: "Root cause analysis", is_correct: false } ], solution: { steps: [ { title: "Methodology", content: "Trade studies help select the best architecture or component among competing options." } ] } },
  // Systems Engineering (3)
  { topic: "Systems Engineering", title: "Verification vs Validation", question: "In systems engineering, 'Validation' answers which of the following questions?", options: [ { text: "Did we build the right system (does it meet user needs)?", is_correct: true }, { text: "Did we build the system right (does it meet specifications)?", is_correct: false }, { text: "Was the project on budget?", is_correct: false }, { text: "Is the software bug-free?", is_correct: false } ], solution: { steps: [ { title: "Definitions", content: "Validation proves the system fulfills its intended purpose in the real world." } ] } },
  { topic: "Systems Engineering", title: "Configuration Management", question: "The discipline of identifying, documenting, and controlling changes to the functional and physical characteristics of a system is known as:", options: [ { text: "Configuration management", is_correct: true }, { text: "Risk management", is_correct: false }, { text: "Quality assurance", is_correct: false }, { text: "Supply chain management", is_correct: false } ], solution: { steps: [ { title: "Discipline", content: "Ensures consistency of a product's performance and attributes over its life." } ] } },
  { topic: "Systems Engineering", title: "Risk Management", question: "In project risk management, calculating the product of a risk's Probability of Occurrence and its Severity of Impact yields the:", options: [ { text: "Risk exposure (or risk score)", is_correct: true }, { text: "Risk tolerance", is_correct: false }, { text: "Risk mitigation", is_correct: false }, { text: "Contingency reserve", is_correct: false } ], solution: { steps: [ { title: "Calculation", content: "Risk = Probability $\\times$ Impact." } ] } }
];

const allNewQuestions = {
  "production": rotateAnswers(productionNew, 0),
  "supply-chain": rotateAnswers(supplyChainNew, 0),
  "ergonomics": rotateAnswers(ergonomicsNew, 0),
  "work-design": rotateAnswers(workDesignNew, 0),
  "quality": rotateAnswers(qualityNew, 0),
  "systems": rotateAnswers(systemsNew, 0)
};

for (const [subj, newQs] of Object.entries(allNewQuestions)) {
  if (questionsObj[subj]) {
    questionsObj[subj].push(...newQs);
  } else {
    questionsObj[subj] = newQs;
  }
}

const updatedJson = JSON.stringify(questionsObj, null, 4);
const prefixContent = fileContent.substring(0, fileContent.indexOf('const QUESTIONS ='));
fs.writeFileSync('questions.js', prefixContent + 'const QUESTIONS = ' + updatedJson + ';\n', 'utf8');
console.log(`Successfully added gaps for remaining IE subjects.`);
