const fs = require('fs');
let fc = fs.readFileSync('questions.js', 'utf8');
const m = fc.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
const Q = JSON.parse(m[1]);

function ra(qs, si) {
  let c = si; const L = ["A","B","C","D"];
  return qs.map(q => {
    let ci = c++ % 4;
    let ct = q.options.find(o=>o.is_correct).text;
    let it = q.options.filter(o=>!o.is_correct).map(o=>o.text);
    let no = []; let ii = 0;
    for(let i=0;i<4;i++) no.push(i===ci?{label:L[i],text:ct,is_correct:true}:{label:L[i],text:it[ii++],is_correct:false});
    q.options=no; if(q.solution) q.solution.final_answer=L[ci]; return q;
  });
}

const riskQ = [
  {topic:"Toxicology",title:"Dose-Response Relationship",question:"In toxicology, the dose-response relationship generally follows what pattern as dose increases?",options:[{text:"Effect increases until a maximum is reached",is_correct:true},{text:"Effect decreases linearly",is_correct:false},{text:"Effect is constant regardless of dose",is_correct:false},{text:"Effect is random",is_correct:false}],solution:{steps:[{title:"Dose-Response",content:"As dose increases, biological effect increases (S-shaped curve) until saturation."}]}},
  {topic:"Toxicology",title:"NOAEL Definition",question:"What does NOAEL stand for in risk assessment?",options:[{text:"No Observed Adverse Effect Level",is_correct:true},{text:"Normal Observed Acceptable Exposure Limit",is_correct:false},{text:"Non-Occupational Allowable Exposure Level",is_correct:false},{text:"Negligible Observable Adverse Exposure Limit",is_correct:false}],solution:{steps:[{title:"NOAEL",content:"NOAEL is the highest dose at which no adverse effects are observed in a study."}]}},
  {topic:"Risk Assessment",title:"Hazard Quotient",question:"In non-cancer risk assessment, a Hazard Quotient (HQ) of less than 1 indicates:",options:[{text:"The exposure is unlikely to cause adverse effects",is_correct:true},{text:"A significant risk of adverse health effects",is_correct:false},{text:"Carcinogenic risk",is_correct:false},{text:"The chemical is not present",is_correct:false}],solution:{steps:[{title:"HQ Interpretation",content:"HQ = Exposure/RfD. HQ < 1 means exposure is below the reference dose, indicating acceptable risk."}]}},
  {topic:"Risk Assessment",title:"Carcinogenic Risk Equation",question:"The excess cancer risk from a carcinogen is calculated as:",options:[{text:"Risk = Exposure × Slope Factor (CSF)",is_correct:true},{text:"Risk = Exposure / Reference Dose",is_correct:false},{text:"Risk = Hazard Index × Exposure",is_correct:false},{text:"Risk = Dose / LD50",is_correct:false}],solution:{steps:[{title:"Cancer Risk",content:"Excess lifetime cancer risk = Average Daily Dose × Cancer Slope Factor (CSF)."}]}},
  {topic:"Toxicology",title:"Routes of Exposure",question:"Which of the following is NOT a primary route of chemical exposure in humans?",options:[{text:"Thermal conduction",is_correct:true},{text:"Inhalation",is_correct:false},{text:"Dermal absorption",is_correct:false},{text:"Ingestion",is_correct:false}],solution:{steps:[{title:"Exposure Routes",content:"The three primary routes are inhalation, ingestion, and dermal absorption. Thermal conduction is a heat transfer mechanism, not a chemical exposure route."}]}},
  {topic:"Risk Assessment",title:"Acceptable Cancer Risk",question:"In environmental risk assessment, EPA considers excess lifetime cancer risk acceptable in the range of:",options:[{text:"$10^{-6}$ to $10^{-4}$",is_correct:true},{text:"$10^{-2}$ to $10^{-1}$",is_correct:false},{text:"$10^{-10}$ to $10^{-8}$",is_correct:false},{text:"Greater than $10^{-4}$",is_correct:false}],solution:{steps:[{title:"EPA Risk Range",content:"EPA's acceptable risk range is one in a million ($10^{-6}$) to one in ten thousand ($10^{-4}$)."}]}},
  {topic:"Toxicology",title:"Bioaccumulation",question:"A substance with a high octanol-water partition coefficient (Kow) is most likely to:",options:[{text:"Bioaccumulate in fatty tissues",is_correct:true},{text:"Remain dissolved in water",is_correct:false},{text:"Quickly biodegrade",is_correct:false},{text:"Volatilize rapidly",is_correct:false}],solution:{steps:[{title:"Kow and Bioaccumulation",content:"High Kow indicates hydrophobicity (fat-soluble), meaning the substance preferentially partitions into fatty tissues and bioaccumulates."}]}},
  {topic:"Risk Assessment",title:"Hazard Index",question:"When multiple chemicals are present, the overall non-cancer Hazard Index (HI) is:",options:[{text:"The sum of individual Hazard Quotients",is_correct:true},{text:"The maximum individual HQ",is_correct:false},{text:"The product of all HQs",is_correct:false},{text:"The average of all HQs",is_correct:false}],solution:{steps:[{title:"Hazard Index",content:"HI = ΣHQ for all chemicals. If HI > 1, there is potential concern for adverse effects."}]}},
  {topic:"Risk Assessment",title:"Reference Dose (RfD)",question:"A chemical has an RfD of $0.003\\ \\text{mg/kg·day}$. A person weighing $70\\ \\text{kg}$ is exposed to $0.1\\ \\text{mg/day}$. What is the Hazard Quotient (HQ)?",options:[{text:"$0.48$",is_correct:true},{text:"$4.8$",is_correct:false},{text:"$0.048$",is_correct:false},{text:"$2.10$",is_correct:false}],solution:{steps:[{title:"Calculate Daily Dose",content:"ADD = 0.1 mg/day ÷ 70 kg = 0.00143 mg/kg·day"},{title:"Calculate HQ",content:"HQ = ADD/RfD = 0.00143/0.003 = 0.48. Since HQ < 1, risk is acceptable."}]}},
  {topic:"Toxicology",title:"Acute vs Chronic Toxicity",question:"A substance that causes adverse effects after a single short-term exposure is classified as:",options:[{text:"Acutely toxic",is_correct:true},{text:"Chronically toxic",is_correct:false},{text:"Subchronically toxic",is_correct:false},{text:"Mutagenic",is_correct:false}],solution:{steps:[{title:"Toxicity Classification",content:"Acute toxicity: single exposure (≤24h). Subchronic: repeated exposure (1-90 days). Chronic: long-term repeated exposure."}]}}
];

const gwSoilsQ = [
  {topic:"Groundwater Flow",title:"Hydraulic Conductivity",question:"A soil sample has a hydraulic conductivity of $5\\times10^{-4}\\ \\text{cm/s}$. It would be classified as:",options:[{text:"Sand or gravel",is_correct:true},{text:"Clay",is_correct:false},{text:"Unfractured igneous rock",is_correct:false},{text:"Dense silt",is_correct:false}],solution:{steps:[{title:"Conductivity Ranges",content:"$K > 10^{-4}$ cm/s is typical of sands and gravels. Clay has $K < 10^{-7}$ cm/s."}]}},
  {topic:"Soil Properties",title:"Porosity vs Hydraulic Conductivity",question:"Total porosity of a soil refers to:",options:[{text:"The ratio of void volume to total soil volume",is_correct:true},{text:"The volume of water held against gravity",is_correct:false},{text:"The rate at which water flows through soil",is_correct:false},{text:"The weight of water per unit volume",is_correct:false}],solution:{steps:[{title:"Porosity Definition",content:"$n = V_{voids}/V_{total}$. Total porosity includes both drainage water and capillary water."}]}},
  {topic:"Groundwater Flow",title:"Aquifer Types",question:"An aquifer confined between two impermeable layers where water rises above the top of the saturated zone when a well is drilled is called:",options:[{text:"An artesian (confined) aquifer",is_correct:true},{text:"An unconfined aquifer",is_correct:false},{text:"A perched aquifer",is_correct:false},{text:"A vadose zone",is_correct:false}],solution:{steps:[{title:"Confined Aquifer",content:"In a confined (artesian) aquifer, water is under pressure. When tapped, it rises above the aquifer top, sometimes reaching the surface (flowing artesian well)."}]}},
  {topic:"Groundwater Flow",title:"Transmissivity",question:"The transmissivity $T$ of an aquifer is related to its hydraulic conductivity $K$ and saturated thickness $b$ by:",options:[{text:"$T = K \\times b$",is_correct:true},{text:"$T = K / b$",is_correct:false},{text:"$T = K + b$",is_correct:false},{text:"$T = K^2 \\times b$",is_correct:false}],solution:{steps:[{title:"Transmissivity",content:"$T = Kb$, where $T$ [m²/day], $K$ [m/day], $b$ [m]. It represents the ease of horizontal groundwater flow."}]}},
  {topic:"Soil Properties",title:"Field Capacity",question:"Field capacity is the moisture content of soil after:",options:[{text:"Free drainage has ceased following saturation",is_correct:true},{text:"Complete oven drying",is_correct:false},{text:"Wilting point is reached by plants",is_correct:false},{text:"A 24-hour submersion",is_correct:false}],solution:{steps:[{title:"Field Capacity",content:"Field capacity is reached 1-2 days after rainfall, when gravity drainage effectively stops. It represents the upper limit of plant-available water."}]}},
  {topic:"Groundwater Flow",title:"Capillary Rise",question:"Capillary rise in soil is greatest in soils with:",options:[{text:"Small pore sizes (fine-grained soils like silt)",is_correct:true},{text:"Large pore sizes (coarse-grained soils like gravel)",is_correct:false},{text:"Zero clay content",is_correct:false},{text:"High hydraulic conductivity",is_correct:false}],solution:{steps:[{title:"Capillary Rise Formula",content:"$h_c \\propto 1/r$, where $r$ is pore radius. Smaller pores → greater capillary rise. Silts have small pores and can have rises of meters."}]}},
  {topic:"Groundwater Flow",title:"Pump Test Analysis",question:"During a pump test, when the water table stops declining and stabilizes, this condition is called:",options:[{text:"Steady state",is_correct:true},{text:"Transient state",is_correct:false},{text:"Superposition",is_correct:false},{text:"Recharge equilibrium",is_correct:false}],solution:{steps:[{title:"Steady State",content:"When pumping rate equals recharge rate, drawdown stabilizes and steady-state conditions are achieved."}]}}
];

if (!Q['risk']) Q['risk'] = [];
Q['risk'].push(...ra(riskQ, Q['risk'].length));
if (!Q['groundwater-soils']) Q['groundwater-soils'] = [];
Q['groundwater-soils'].push(...ra(gwSoilsQ, Q['groundwater-soils'].length));

const nc = fc.replace(/const QUESTIONS = \{[\s\S]*\};?\s*$/, `const QUESTIONS = ${JSON.stringify(Q, null, 4)};\n`);
fs.writeFileSync('questions.js', nc);
console.log(`risk: ${Q['risk'].length}, groundwater-soils: ${Q['groundwater-soils'].length}`);
