const fs = require('fs');
let fc = fs.readFileSync('questions.js', 'utf8');
const m = fc.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
const Q = JSON.parse(m[1]);

function ra(qs, si) {
  let c = si; const L = ["A","B","C","D"];
  return qs.map(q => {
    let ci = c++ % 4;
    let ct = q.options.find(o=>o.is_correct).text;
    let it = q.options.filter(o=>!o.is_correct).map(o=>o.text);
    let no = []; let ii = 0;
    for(let i=0;i<4;i++) no.push(i===ci?{label:L[i],text:ct,is_correct:true}:{label:L[i],text:it[ii++],is_correct:false});
    q.options=no; if(q.solution) q.solution.final_answer=L[ci]; return q;
  });
}

const balancesQ = [
  {topic:"Material Balances",title:"Degrees of Freedom",question:"In material balance calculations, a process has zero degrees of freedom when:",options:[{text:"The number of unknown variables equals the number of independent equations",is_correct:true},{text:"The number of unknown variables exceeds the number of independent equations",is_correct:false},{text:"There are no constraints on the system",is_correct:false},{text:"The system operates at steady state",is_correct:false}],solution:{steps:[{title:"Degrees of Freedom",content:"Degrees of Freedom (DOF) = (Number of unknowns) - (Number of independent equations). When DOF = 0, the system is exactly specified and can be solved uniquely."}]}},
  {topic:"Material Balances",title:"Recycle Stream",question:"What is the primary purpose of a recycle stream in a chemical process?",options:[{text:"To return unreacted reactants to the reactor to improve overall conversion",is_correct:true},{text:"To remove inert gases from the system",is_correct:false},{text:"To increase the temperature of the feed",is_correct:false},{text:"To separate the final product",is_correct:false}],solution:{steps:[{title:"Recycle Streams",content:"Recycle streams take unreacted material from downstream separators and feed it back to the reactor, increasing the overall conversion of the process."}]}},
  {topic:"Energy Balances",title:"Heat of Reaction",question:"The standard heat of reaction ($\\Delta H_r^\\circ$) is defined as the enthalpy change when:",options:[{text:"Molar quantities of reactants specified by the stoichiometric equation react completely at standard conditions ($25^\\circ\\text{C}$, $1\\ \\text{atm}$)",is_correct:true},{text:"One mole of a substance is formed from its elements",is_correct:false},{text:"One mole of a substance is completely combusted",is_correct:false},{text:"A reaction occurs at adiabatic conditions",is_correct:false}],solution:{steps:[{title:"Standard Heat of Reaction",content:"$\\Delta H_r^\\circ$ is the enthalpy change for a specific stoichiometric reaction where all reactants and products are at standard temperature and pressure ($25^\\circ\\text{C}$ and $1\\ \\text{atm}$)."}]}},
  {topic:"Material Balances",title:"Purge Stream",question:"Why is a purge stream necessary in a process with a recycle loop?",options:[{text:"To prevent the accumulation of inert or unwanted substances in the recycle loop",is_correct:true},{text:"To provide a sample point for quality control",is_correct:false},{text:"To cool the recycle stream",is_correct:false},{text:"To recover the final product",is_correct:false}],solution:{steps:[{title:"Purge Purpose",content:"If a feed contains inerts that do not react, recycling will cause them to build up indefinitely. A purge stream bleeds off a fraction of the recycle to maintain a steady concentration of inerts."}]}},
  {topic:"Energy Balances",title:"Heat Capacity",question:"The heat required to raise the temperature of a substance is given by $Q = m C_p \\Delta T$. What does $C_p$ represent?",options:[{text:"Specific heat capacity at constant pressure",is_correct:true},{text:"Specific heat capacity at constant volume",is_correct:false},{text:"Heat of vaporization",is_correct:false},{text:"Thermal conductivity",is_correct:false}],solution:{steps:[{title:"Specific Heat",content:"$C_p$ is the specific heat capacity at constant pressure, which is the amount of heat energy required to raise the temperature of a unit mass of a substance by one degree."}]}},
  {topic:"Material Balances",title:"Limiting Reactant",question:"In a chemical reaction, the limiting reactant is the one that:",options:[{text:"Would be completely consumed first if the reaction proceeded to completion",is_correct:true},{text:"Has the lowest mass in the feed",is_correct:false},{text:"Has the lowest stoichiometric coefficient",is_correct:false},{text:"Is the most expensive",is_correct:false}],solution:{steps:[{title:"Limiting Reactant",content:"The limiting reactant determines the maximum theoretical yield of the products. It is the reactant present in the smallest stoichiometric amount relative to the balanced equation."}]}},
  {topic:"Energy Balances",title:"Latent Heat",question:"Latent heat refers to the energy required to:",options:[{text:"Change the phase of a substance without changing its temperature",is_correct:true},{text:"Raise the temperature of a substance by $1^\\circ\\text{C}$",is_correct:false},{text:"Break chemical bonds during a reaction",is_correct:false},{text:"Overcome friction in a fluid flow",is_correct:false}],solution:{steps:[{title:"Latent Heat",content:"Latent heat is the heat absorbed or released during a phase change (like melting or boiling) at a constant temperature and pressure."}]}}
];

const reactionEngQ = [
  {topic:"Kinetics",title:"Arrhenius Equation",question:"According to the Arrhenius equation ($k = A e^{-E_a/RT}$), how does the rate constant $k$ typically respond to an increase in temperature $T$?",options:[{text:"It increases exponentially",is_correct:true},{text:"It decreases exponentially",is_correct:false},{text:"It increases linearly",is_correct:false},{text:"It remains constant",is_correct:false}],solution:{steps:[{title:"Arrhenius Equation",content:"Because of the negative exponent $-E_a/(RT)$, as $T$ increases, the exponent becomes less negative, causing $k$ to increase exponentially."}]}},
  {topic:"Reactor Design",title:"Plug Flow Reactor (PFR)",question:"In an ideal Plug Flow Reactor (PFR), it is assumed that:",options:[{text:"There is no axial mixing, but perfect radial mixing",is_correct:true},{text:"There is perfect mixing in all directions",is_correct:false},{text:"The concentration is uniform throughout the reactor",is_correct:false},{text:"The residence time is highly variable",is_correct:false}],solution:{steps:[{title:"PFR Assumptions",content:"An ideal PFR assumes that fluid travels as a 'plug' with a uniform velocity profile. There is perfect mixing radially, but absolutely no mixing axially (in the direction of flow)."}]}},
  {topic:"Reactor Design",title:"CSTR vs PFR",question:"For a given volume and isothermal first-order reaction ($A \\rightarrow P$), which reactor type generally achieves a higher conversion?",options:[{text:"Plug Flow Reactor (PFR)",is_correct:true},{text:"Continuous Stirred-Tank Reactor (CSTR)",is_correct:false},{text:"Both achieve the exact same conversion",is_correct:false},{text:"Depends entirely on the pressure",is_correct:false}],solution:{steps:[{title:"Reactor Comparison",content:"For reactions with order $> 0$ (like first-order), a PFR is more efficient than a CSTR of the same volume because the average reactant concentration (driving force) remains higher along the PFR's length."}]}},
  {topic:"Kinetics",title:"Zero-Order Reaction",question:"In a zero-order reaction, the rate of reaction is:",options:[{text:"Independent of the reactant concentration",is_correct:true},{text:"Directly proportional to the reactant concentration",is_correct:false},{text:"Proportional to the square of the reactant concentration",is_correct:false},{text:"Dependent only on temperature",is_correct:false}],solution:{steps:[{title:"Zero-Order Kinetics",content:"For a zero-order reaction, the rate law is $r = k[A]^0 = k$. The rate is constant and independent of the concentration of the reactant."}]}},
  {topic:"Reactor Design",title:"Residence Time Distribution (RTD)",question:"What does the Residence Time Distribution (RTD) of a reactor describe?",options:[{text:"The probability distribution of time that fluid elements spend inside the reactor",is_correct:true},{text:"The spatial distribution of temperature within the reactor",is_correct:false},{text:"The exact chemical composition of the effluent",is_correct:false},{text:"The mechanical stress distribution on the reactor walls",is_correct:false}],solution:{steps:[{title:"RTD Meaning",content:"RTD ($E(t)$) characterizes the macroscopic mixing in a reactor, detailing how long different fluid elements remain inside before exiting."}]}},
  {topic:"Kinetics",title:"Activation Energy",question:"Activation energy ($E_a$) is best defined as:",options:[{text:"The minimum energy required to initiate a chemical reaction",is_correct:true},{text:"The total energy released by an exothermic reaction",is_correct:false},{text:"The energy difference between reactants and products",is_correct:false},{text:"The kinetic energy of the molecules at standard temperature",is_correct:false}],solution:{steps:[{title:"Activation Energy",content:"$E_a$ is the energy barrier that must be overcome for reactants to reach the transition state and convert into products."}]}},
  {topic:"Reactor Design",title:"Batch Reactor",question:"A key characteristic of an ideal batch reactor is that:",options:[{text:"There is no inflow or outflow of mass during the reaction",is_correct:true},{text:"Reactants are continuously fed and products continuously removed",is_correct:false},{text:"Concentration varies spatially but is constant with time",is_correct:false},{text:"It operates strictly at steady state",is_correct:false}],solution:{steps:[{title:"Batch Reactor Operation",content:"In a batch reactor, all reactants are loaded initially, mixed, and allowed to react for a specific time. There is no mass flow across its boundaries during the reaction; concentration changes over time but is spatially uniform."}]}}
];


if (!Q['balances']) Q['balances'] = [];
Q['balances'].push(...ra(balancesQ, Q['balances'].length));
if (!Q['reaction-eng']) Q['reaction-eng'] = [];
Q['reaction-eng'].push(...ra(reactionEngQ, Q['reaction-eng'].length));

const nc = fc.replace(/const QUESTIONS = \{[\s\S]*\};?\s*$/, `const QUESTIONS = ${JSON.stringify(Q, null, 4)};\n`);
fs.writeFileSync('questions.js', nc);
console.log(`balances: ${Q['balances'].length}, reaction-eng: ${Q['reaction-eng'].length}`);
