const fs = require('fs');
let fc = fs.readFileSync('questions.js', 'utf8');
const m = fc.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
const Q = JSON.parse(m[1]);

function ra(qs, si) {
  let c = si; const L = ["A","B","C","D"];
  return qs.map(q => {
    let ci = c++ % 4;
    let ct = q.options.find(o=>o.is_correct).text;
    let it = q.options.filter(o=>!o.is_correct).map(o=>o.text);
    let no = []; let ii = 0;
    for(let i=0;i<4;i++) no.push(i===ci?{label:L[i],text:ct,is_correct:true}:{label:L[i],text:it[ii++],is_correct:false});
    q.options=no; if(q.solution) q.solution.final_answer=L[ci]; return q;
  });
}

const engMgmtQ = [
  {topic:"Project Management",title:"Gantt Chart",question:"A Gantt chart is primarily used in project management to:",options:[{text:"Visualize the project schedule and task durations",is_correct:true},{text:"Calculate the total cost of the project",is_correct:false},{text:"Identify the optimal critical path mathematically",is_correct:false},{text:"Determine the organizational hierarchy",is_correct:false}],solution:{steps:[{title:"Gantt Chart Purpose",content:"A Gantt chart is a bar chart that illustrates a project schedule, showing the start and finish dates of the terminal elements and summary elements of a project."}]}},
  {topic:"Project Management",title:"PERT Expected Time",question:"In PERT (Program Evaluation and Review Technique), the expected time $T_e$ for an activity is calculated using optimistic ($O$), most likely ($M$), and pessimistic ($P$) estimates by the formula:",options:[{text:"$T_e = (O + 4M + P) / 6$",is_correct:true},{text:"$T_e = (O + M + P) / 3$",is_correct:false},{text:"$T_e = (O + 2M + P) / 4$",is_correct:false},{text:"$T_e = (O + P) / 2$",is_correct:false}],solution:{steps:[{title:"PERT Formula",content:"The PERT expected time is a weighted average heavily weighting the most likely estimate: $T_e = \\frac{O + 4M + P}{6}$."}]}},
  {topic:"Project Management",title:"Scope Creep",question:"'Scope creep' in engineering management refers to:",options:[{text:"The uncontrolled expansion to product or project scope without adjustments to time, cost, and resources",is_correct:true},{text:"The gradual degradation of project quality",is_correct:false},{text:"The slow process of acquiring project funding",is_correct:false},{text:"A planned, phased approach to project delivery",is_correct:false}],solution:{steps:[{title:"Scope Creep Definition",content:"Scope creep happens when project requirements or features increase beyond the original plan without corresponding increases in budget or schedule."}]}},
  {topic:"Organizational Behavior",title:"Matrix Organization",question:"In a matrix organizational structure, an engineer typically reports to:",options:[{text:"Both a functional manager and a project manager",is_correct:true},{text:"Only a project manager",is_correct:false},{text:"Only a functional manager",is_correct:false},{text:"The client directly",is_correct:false}],solution:{steps:[{title:"Matrix Structure",content:"A matrix structure creates dual lines of authority, typically combining functional (departmental) and product/project reporting lines."}]}},
  {topic:"Project Management",title:"Work Breakdown Structure",question:"What is the primary purpose of a Work Breakdown Structure (WBS)?",options:[{text:"To decompose the total scope of work into smaller, manageable components",is_correct:true},{text:"To schedule the daily tasks of individual workers",is_correct:false},{text:"To calculate the project's internal rate of return",is_correct:false},{text:"To identify project risks and mitigation strategies",is_correct:false}],solution:{steps:[{title:"WBS Purpose",content:"The WBS is a hierarchical decomposition of the total scope of work to be carried out by the project team to accomplish the project objectives and create the required deliverables."}]}},
  {topic:"Project Management",title:"Earned Value Management",question:"In Earned Value Management, if the Cost Performance Index (CPI) is greater than 1.0, it indicates that the project is:",options:[{text:"Under budget",is_correct:true},{text:"Over budget",is_correct:false},{text:"Behind schedule",is_correct:false},{text:"Ahead of schedule",is_correct:false}],solution:{steps:[{title:"CPI Interpretation",content:"CPI = Earned Value (EV) / Actual Cost (AC). A CPI > 1.0 means you are earning more value than you are spending (under budget)."}]}},
  {topic:"Project Management",title:"Float or Slack",question:"In project network analysis, the 'float' or 'slack' of an activity represents:",options:[{text:"The amount of time an activity can be delayed without delaying the project completion date",is_correct:true},{text:"The duration of the activity",is_correct:false},{text:"The cost variance of the activity",is_correct:false},{text:"The amount of time the activity is expected to take",is_correct:false}],solution:{steps:[{title:"Float/Slack Definition",content:"Total float (slack) is the difference between the late start and early start dates (or late finish and early finish) of an activity."}]}}
];

const compToolsQ = [
  {topic:"Spreadsheets",title:"Absolute Cell Reference",question:"In spreadsheet software (like Excel), which symbol is used to create an absolute cell reference?",options:[{text:"$",is_correct:true},{text:"#",is_correct:false},{text:"@",is_correct:false},{text:"&",is_correct:false}],solution:{steps:[{title:"Absolute References",content:"The dollar sign ($) is used to fix the column and/or row reference (e.g., $A$1) so it doesn't change when the formula is copied."}]}},
  {topic:"Spreadsheets",title:"VLOOKUP Function",question:"The VLOOKUP function in a spreadsheet is primarily used to:",options:[{text:"Search for a value in the first column of a table and return a value in the same row from another column",is_correct:true},{text:"Calculate the variance of a dataset",is_correct:false},{text:"Visually look up spelling errors in a document",is_correct:false},{text:"Search horizontally across a row",is_correct:false}],solution:{steps:[{title:"VLOOKUP Definition",content:"VLOOKUP stands for Vertical Lookup. It searches vertically down the first column of a range and returns a value in the same row."}]}},
  {topic:"Mathematical Software",title:"Numerical Integration",question:"When using mathematical software to numerically evaluate a definite integral, which common rule or method is often applied behind the scenes?",options:[{text:"Simpson's Rule",is_correct:true},{text:"L'Hôpital's Rule",is_correct:false},{text:"Cramer's Rule",is_correct:false},{text:"The Chain Rule",is_correct:false}],solution:{steps:[{title:"Numerical Methods",content:"Simpson's rule is a standard numerical method for approximating the definite integral of a function using parabolic arcs."}]}},
  {topic:"Spreadsheets",title:"Goal Seek",question:"The 'Goal Seek' tool in spreadsheet software is an example of:",options:[{text:"A 'what-if' analysis tool used to find the input value needed to achieve a specific target output",is_correct:true},{text:"A function that automatically creates charts",is_correct:false},{text:"A database sorting algorithm",is_correct:false},{text:"A statistical regression tool",is_correct:false}],solution:{steps:[{title:"Goal Seek Tool",content:"Goal Seek iteratively adjusts one input cell until a formula dependent on that cell reaches a specified target value."}]}},
  {topic:"Mathematical Software",title:"Solving Linear Equations",question:"In mathematical software like MATLAB, a system of linear equations represented by the matrix equation $Ax = b$ is typically solved using:",options:[{text:"Matrix inversion or Gaussian elimination ($x = A \\backslash b$)",is_correct:true},{text:"Numerical integration",is_correct:false},{text:"The Newton-Raphson method",is_correct:false},{text:"Monte Carlo simulation",is_correct:false}],solution:{steps:[{title:"Solving Linear Systems",content:"Linear systems are solved using matrix division (which uses Gaussian elimination under the hood) or by multiplying by the inverse of A ($x = A^{-1}b$)."}]}},
  {topic:"Spreadsheets",title:"Pivot Tables",question:"What is the primary function of a Pivot Table in a spreadsheet?",options:[{text:"To summarize, analyze, explore, and present large amounts of data",is_correct:true},{text:"To link multiple spreadsheets together securely",is_correct:false},{text:"To format data into a printable layout",is_correct:false},{text:"To act as a primary key in a relational database",is_correct:false}],solution:{steps:[{title:"Pivot Table Purpose",content:"Pivot tables are powerful tools for quickly summarizing large datasets, allowing users to group data, count, total, or average it automatically."}]}},
  {topic:"Mathematical Software",title:"Root Finding",question:"The Newton-Raphson method, often implemented in engineering software, is used primarily to:",options:[{text:"Find the roots (zeros) of a real-valued function",is_correct:true},{text:"Solve ordinary differential equations",is_correct:false},{text:"Calculate the eigenvectors of a matrix",is_correct:false},{text:"Perform symbolic integration",is_correct:false}],solution:{steps:[{title:"Newton-Raphson Method",content:"The Newton-Raphson method is an iterative numerical root-finding algorithm that uses the tangent of a function to approximate its roots."}]}}
];


if (!Q['eng-mgmt']) Q['eng-mgmt'] = [];
Q['eng-mgmt'].push(...ra(engMgmtQ, Q['eng-mgmt'].length));
if (!Q['comp-tools']) Q['comp-tools'] = [];
Q['comp-tools'].push(...ra(compToolsQ, Q['comp-tools'].length));

const nc = fc.replace(/const QUESTIONS = \{[\s\S]*\};?\s*$/, `const QUESTIONS = ${JSON.stringify(Q, null, 4)};\n`);
fs.writeFileSync('questions.js', nc);
console.log(`eng-mgmt: ${Q['eng-mgmt'].length}, comp-tools: ${Q['comp-tools'].length}`);
