const fs = require('fs');
let fc = fs.readFileSync('questions.js', 'utf8');
const m = fc.match(/const QUESTIONS = (\{[\s\S]*\});?\s*$/);
const Q = JSON.parse(m[1]);

function ra(qs, si) {
  let c = si; const L = ["A","B","C","D"];
  return qs.map(q => {
    let ci = c++ % 4;
    let ct = q.options.find(o=>o.is_correct).text;
    let it = q.options.filter(o=>!o.is_correct).map(o=>o.text);
    let no = []; let ii = 0;
    for(let i=0;i<4;i++) no.push(i===ci?{label:L[i],text:ct,is_correct:true}:{label:L[i],text:it[ii++],is_correct:false});
    q.options=no; if(q.solution) q.solution.final_answer=L[ci]; return q;
  });
}

const chemBioQ = [
  {topic:"Biochemistry",title:"Enzyme Action",question:"Enzymes act as biological catalysts primarily by:",options:[{text:"Lowering the activation energy of the reaction",is_correct:true},{text:"Increasing the temperature of the cell",is_correct:false},{text:"Changing the equilibrium constant of the reaction",is_correct:false},{text:"Being consumed in the reaction",is_correct:false}],solution:{steps:[{title:"Enzyme Function",content:"Enzymes speed up chemical reactions in biological systems by providing an alternative reaction pathway with a lower activation energy barrier."}]}},
  {topic:"Biochemistry",title:"Michaelis-Menten Kinetics",question:"In Michaelis-Menten enzyme kinetics, $K_m$ (the Michaelis constant) represents:",options:[{text:"The substrate concentration at which the reaction velocity is half of its maximum ($V_{max}/2$)",is_correct:true},{text:"The maximum velocity of the reaction",is_correct:false},{text:"The concentration of the enzyme",is_correct:false},{text:"The total product formed",is_correct:false}],solution:{steps:[{title:"$K_m$ Definition",content:"$K_m$ is an inverse measure of the affinity of the enzyme for its substrate. It is specifically the substrate concentration that yields $1/2 V_{max}$."}]}},
  {topic:"General Chemistry",title:"Ideal Gas Law",question:"At Standard Temperature and Pressure (STP), what is the approximate volume of 1 mole of an ideal gas?",options:[{text:"22.4 Liters",is_correct:true},{text:"1.0 Liter",is_correct:false},{text:"100 Liters",is_correct:false},{text:"24.5 Liters",is_correct:false}],solution:{steps:[{title:"Molar Volume at STP",content:"By definition ($T=273.15$ K, $P=1$ atm), using $V = nRT/P$, the volume of 1 mole of ideal gas is $22.414$ L."}]}},
  {topic:"General Chemistry",title:"Gibbs Free Energy",question:"A chemical reaction is spontaneous under conditions of constant temperature and pressure if:",options:[{text:"$\\Delta G < 0$",is_correct:true},{text:"$\\Delta G > 0$",is_correct:false},{text:"$\\Delta H > 0$",is_correct:false},{text:"$\\Delta S < 0$",is_correct:false}],solution:{steps:[{title:"Spontaneity",content:"The change in Gibbs Free Energy ($\\Delta G = \\Delta H - T\\Delta S$) must be negative for a process to be thermodynamically spontaneous."}]}},
  {topic:"Biochemistry",title:"ATP Function",question:"Adenosine triphosphate (ATP) serves primarily as:",options:[{text:"The main energy currency of the cell",is_correct:true},{text:"A long-term structural component of the cell membrane",is_correct:false},{text:"A carrier of genetic information",is_correct:false},{text:"A digestive enzyme",is_correct:false}],solution:{steps:[{title:"ATP Role",content:"ATP stores and transports chemical energy within cells for metabolism. The hydrolysis of its high-energy phosphate bonds releases energy."}]}},
  {topic:"General Chemistry",title:"VSEPR Theory",question:"According to VSEPR theory, what is the molecular geometry of methane ($CH_4$)?",options:[{text:"Tetrahedral",is_correct:true},{text:"Square planar",is_correct:false},{text:"Trigonal planar",is_correct:false},{text:"Linear",is_correct:false}],solution:{steps:[{title:"Methane Geometry",content:"Carbon has 4 valence electrons forming 4 single bonds with Hydrogen, and 0 lone pairs. This results in a $AX_4$ tetrahedral geometry with $109.5^\\circ$ bond angles."}]}},
  {topic:"Biochemistry",title:"Proteins",question:"The primary structure of a protein refers to:",options:[{text:"The linear sequence of amino acids in the polypeptide chain",is_correct:true},{text:"The local folding into alpha helices and beta sheets",is_correct:false},{text:"The overall 3D shape of a single protein molecule",is_correct:false},{text:"The association of multiple protein subunits",is_correct:false}],solution:{steps:[{title:"Protein Structure Levels",content:"Primary = sequence; Secondary = local folding (alpha/beta); Tertiary = 3D folding; Quaternary = multi-subunit arrangement."}]}}
];

const processControlQ = [
  {topic:"Control Loops",title:"Feedback Control",question:"In a basic feedback control loop, the controller takes action based on:",options:[{text:"The error signal (the difference between the setpoint and the measured variable)",is_correct:true},{text:"Predictions of future disturbances",is_correct:false},{text:"Measurements of incoming disturbances before they affect the process",is_correct:false},{text:"A fixed, pre-programmed schedule",is_correct:false}],solution:{steps:[{title:"Feedback Logic",content:"Feedback control measures the actual output, compares it to the desired setpoint to calculate an error, and adjusts the input to minimize that error."}]}},
  {topic:"Control Loops",title:"Feedforward Control",question:"What is the primary advantage of feedforward control over feedback control?",options:[{text:"It can take corrective action before the measured disturbance affects the process output",is_correct:true},{text:"It does not require a mathematical model of the process",is_correct:false},{text:"It automatically eliminates steady-state offset without integral action",is_correct:false},{text:"It is simpler and cheaper to implement",is_correct:false}],solution:{steps:[{title:"Feedforward Advantage",content:"By measuring a disturbance directly, feedforward control anticipates its effect and preemptively adjusts the manipulated variable."}]}},
  {topic:"Tuning",title:"Ziegler-Nichols Method",question:"The Ziegler-Nichols ultimate gain (closed-loop) tuning method involves:",options:[{text:"Increasing the proportional gain until continuous, sustained oscillations are observed",is_correct:true},{text:"Applying a step change to the open-loop process and measuring the reaction rate",is_correct:false},{text:"Setting derivative time to zero and integrating the error",is_correct:false},{text:"Using trial-and-error without a specific procedure",is_correct:false}],solution:{steps:[{title:"Z-N Closed-Loop Method",content:"The controller is set to P-only mode, and the gain ($K_c$) is increased until the process output exhibits sustained oscillations. This gain is the ultimate gain ($K_u$)."}]}},
  {topic:"Control Loops",title:"Final Control Element",question:"In a typical chemical plant control loop, the 'final control element' is most commonly a:",options:[{text:"Pneumatic control valve",is_correct:true},{text:"Thermocouple",is_correct:false},{text:"PID Controller algorithm",is_correct:false},{text:"Transmitter",is_correct:false}],solution:{steps:[{title:"Final Control Element",content:"The final control element actually changes the physical process (e.g., altering flow rate). The most common type is an automated control valve."}]}},
  {topic:"Tuning",title:"Derivative Action",question:"Derivative (D) action in a PID controller is primarily used to:",options:[{text:"Improve process stability and speed of response by anticipating error trends",is_correct:true},{text:"Eliminate steady-state offset",is_correct:false},{text:"Filter out high-frequency noise from the sensor",is_correct:false},{text:"Provide a baseline, proportional response to error",is_correct:false}],solution:{steps:[{title:"Derivative Action",content:"Derivative action responds to the rate of change of the error, providing a 'braking' effect that reduces overshoot and improves stability. It is sensitive to noise, however."}]}},
  {topic:"Control Loops",title:"Laplace Transforms",question:"In control systems engineering, why are Laplace transforms commonly used?",options:[{text:"They convert differential equations in the time domain into algebraic equations in the s-domain",is_correct:true},{text:"They convert analog signals to digital signals",is_correct:false},{text:"They are required to program PLCs",is_correct:false},{text:"They eliminate the need for sensors",is_correct:false}],solution:{steps:[{title:"Laplace Transform Use",content:"Laplace transforms simplify the analysis and design of linear dynamic systems by turning calculus problems (differential equations) into simpler algebra problems (transfer functions)."}]}},
  {topic:"Tuning",title:"Quarter Decay Ratio",question:"A common heuristic goal in control loop tuning is the 'quarter decay ratio', meaning:",options:[{text:"Each successive peak of the oscillating response is 1/4 the amplitude of the previous peak",is_correct:true},{text:"The response settles within a quarter of a minute",is_correct:false},{text:"The error is reduced by 25% on each iteration",is_correct:false},{text:"The controller gain is set to 1/4 of the ultimate gain",is_correct:false}],solution:{steps:[{title:"Quarter Decay",content:"The quarter decay ratio is a classical compromise between a fast response (which might be too oscillatory) and a sluggish response (which takes too long to settle)."}]}}
];

if (!Q['chem-bio']) Q['chem-bio'] = [];
Q['chem-bio'].push(...ra(chemBioQ, Q['chem-bio'].length));
if (!Q['process-control']) Q['process-control'] = [];
Q['process-control'].push(...ra(processControlQ, Q['process-control'].length));

const nc = fc.replace(/const QUESTIONS = \{[\s\S]*\};?\s*$/, `const QUESTIONS = ${JSON.stringify(Q, null, 4)};\n`);
fs.writeFileSync('questions.js', nc);
console.log(`chem-bio: ${Q['chem-bio'].length}, process-control: ${Q['process-control'].length}`);
